-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_0_36_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_0_36_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101011011011101100111000010", 1 => "00111100111110111101000001011011", 2 => "10111101011111001101111011100011", 3 => "10111101101011000010000101011100", 
    4 => "10111101101011111111001000011011", 5 => "10111101100111001110001010001111", 6 => "10111101101010110010011000111001", 7 => "10111101110010110001010111111001", 
    8 => "10111100000011001101111010100000", 9 => "10111101101110000010010001001111", 10 => "00111101001000101010001111001111", 11 => "00111101001011110101010001001100", 
    12 => "10111101110101000001101101110110", 13 => "10111100011110111101011010100110", 14 => "10111100010101001001110101111100", 15 => "10111110000010001001100011110110", 
    16 => "00111100101101111011110100000110", 17 => "00111101010111001100110010001010", 18 => "00111101110110100000010010001110", 19 => "00111100110110100000100111001100", 
    20 => "00111110000101000000011000111010", 21 => "00111110001111010100101101101010", 22 => "10111101011111100111111100101100", 23 => "00111011000101000100111011010111", 
    24 => "00111101010111010000011000110110", 25 => "10111101101000101010010011011011", 26 => "00111101011100110100110101101010", 27 => "10111101001010001110010011111100", 
    28 => "00111101000011100011100010101000", 29 => "00111110000111100101110010010010", 30 => "10111101001101010101011110011011", 31 => "00111101100011001110000111000110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

