-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_40_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_40_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101010110101111101011111000", 1 => "00111100000010101011100100101100", 2 => "00111101110100001100001011000110", 3 => "00111110001000010000101001010111", 
    4 => "10111001010100011011011100010111", 5 => "00111101001111001011001011011001", 6 => "00111100111001111000000110000100", 7 => "10111101010111000001011000010110", 
    8 => "00111101000001000110011100111000", 9 => "00111100010000110110010101000101", 10 => "00111101010010101001100010101011", 11 => "10111011011010101011111111111101", 
    12 => "00111100100001100110001111000111", 13 => "00111011111110110000100100100000", 14 => "10111100111101110010000011001001", 15 => "00111101001001000100001100001011", 
    16 => "10111101010110011000010110101101", 17 => "10111011010010111001111011001111", 18 => "10111011001000100111011010111000", 19 => "10111011111100101101011111111001", 
    20 => "10111011101011011001101011011000", 21 => "00111100001000000001101010111101", 22 => "10111100011011001011001100011100", 23 => "00111101100110111100101010010111", 
    24 => "00111100011011111000100010111001", 25 => "00111101100001001111100101111111", 26 => "10111100001110110000111001011110", 27 => "00111101100001101110011011011010", 
    28 => "00111101110111110000100110010110", 29 => "00111100010111110110010101010110", 30 => "10111101100101111000100100011110", 31 => "00111101011010001001001000100101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

