-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_16_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_16_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101000100111000011110011100", 1 => "10111100011100001010010111110000", 2 => "00111110010100100100000111000100", 3 => "00111100101001100101010010010011", 
    4 => "00111110100100000010111010101001", 5 => "10111100011001101000111000111111", 6 => "00111111000000101110011100111110", 7 => "00111110001101000001110011000101", 
    8 => "10111101101100010111110111110010", 9 => "00111101101111010010110001111100", 10 => "00111111000001001001110100010111", 11 => "10111101111111100110010001101111", 
    12 => "00111101100001101111101001000000", 13 => "10111101011001100100110000110000", 14 => "00111110010100011000101011001010", 15 => "00111101010101110000011000001100", 
    16 => "00111101101101111010000010110110", 17 => "10111101101111100101001100100010", 18 => "00111011101001000000000011111100", 19 => "00111100111100101001101100101000", 
    20 => "00111101100111100001001000011111", 21 => "10111110101100110101011100011101", 22 => "00111110000001101001010010001010", 23 => "00111101100001101010011001011101", 
    24 => "00111110010011111100101110010010", 25 => "10111101101010001010010110001011", 26 => "10111101001001000000011000111010", 27 => "10111100000110100111110000011000", 
    28 => "10111100100010110011111101100100", 29 => "00111110010000001110011011110011", 30 => "10111101011100110100100100111000", 31 => "10111110001000000011011001000100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

