-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_16_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_16_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101010111101011110010000100", 1 => "00111001111100110100010100000111", 2 => "10111101100100010110000100011100", 3 => "00111100101001000011001101010001", 
    4 => "00111001001101000101101011100110", 5 => "10111101100110001010110100100101", 6 => "00111101110011000100111101111111", 7 => "00111011000111101101101111111001", 
    8 => "00111011101101010110011101010101", 9 => "00111100111000011010000111011100", 10 => "10111101010001001000100011000110", 11 => "00111100101010100100100110000000", 
    12 => "00111101100110101101101110000011", 13 => "10111011101010011001101101101111", 14 => "00111101000101000011110100000100", 15 => "00111101110111000111000101010000", 
    16 => "00111101000011010011101111110011", 17 => "10111101000110101000010110001000", 18 => "00111101001111001111101100110011", 19 => "10111101001000111100101001110101", 
    20 => "00111101000110110010100100011100", 21 => "00111101001011000100100100110100", 22 => "10111101010100111101100101100110", 23 => "00111100111100010110101100010010", 
    24 => "00111101100111001011101100111101", 25 => "10111101000000100100001111011101", 26 => "10111101011001100011110001110101", 27 => "10111110000100011010101000111111", 
    28 => "10111101011101100110000011100101", 29 => "00111011001000000010101110000100", 30 => "00111100100111110110111011000110", 31 => "00111100100001101110111000110001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

