-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_16_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_16_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101101100011001011000010000", 1 => "00111100111011000100110001011001", 2 => "10111101001001100100111001001000", 3 => "10111100000100111111111100100110", 
    4 => "10111100001101111010111001011000", 5 => "10111101101011100100100101101111", 6 => "00111101011111010101111111011101", 7 => "10111100110110111110011111110011", 
    8 => "00111100101011100011111001101100", 9 => "10111100010100110000011010100011", 10 => "10111101000011001000011110011000", 11 => "00111100110101000100110111001011", 
    12 => "10111101010110000111100100111110", 13 => "10111101010000110111010100000000", 14 => "00111101000000100001001110100001", 15 => "00111110000101000001111111101011", 
    16 => "00111110010000000111001001001011", 17 => "10111101010010011001101111110110", 18 => "10111100101111100000000101011000", 19 => "10111101011101011101101010101101", 
    20 => "00111011001010001011000010001110", 21 => "00111100111000110111000101010100", 22 => "00111101011110011101100100001010", 23 => "10111101011100110010101111011100", 
    24 => "00111100100010001011101110010000", 25 => "10111101011110100001011011101000", 26 => "10111100100001110110111000011110", 27 => "00111100010100001000010011101000", 
    28 => "10111101001110000110111000111011", 29 => "10111101101101100110110001101110", 30 => "10111011110111110101100011000001", 31 => "00111101101101000100111001010001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

