-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_82_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_82_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101001110011111011101110011", 1 => "00111101100010000100111100001001", 2 => "10111100011100010011100010111101", 3 => "00111100111000010101110010100111", 
    4 => "10111100101100010111000001010000", 5 => "00111101000010111111001010110010", 6 => "10111101101011011111000001001110", 7 => "00111101110000011110110111100001", 
    8 => "10111100111111000101101011000100", 9 => "00111100111011110001001101001001", 10 => "10111100010011111001111000111000", 11 => "10111101100011101000100101100101", 
    12 => "00111100101100010011101111100010", 13 => "00111101100001110001000011001011", 14 => "10111101010101011001010111111111", 15 => "00111100001110101111110110010111", 
    16 => "00111100100111100110101010111010", 17 => "10111101100001010111111010101010", 18 => "10111101010000101101100011000011", 19 => "00111100110011010100011001101111", 
    20 => "10111100110001100001000011110001", 21 => "10111101101100001001111110100101", 22 => "00111101001000000101101010110100", 23 => "00111101100101010000110010100010", 
    24 => "00111101101111100001010101000100", 25 => "10111101100101001011100111001011", 26 => "00111101000001010111111000100100", 27 => "10111101110111001000011111011011", 
    28 => "00111101000010010001100011100011", 29 => "10111101001000111001000011001001", 30 => "10111101100111001001001001011000", 31 => "10111101110101011001011110010010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

