-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_38_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_38_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110011110100110011010011001", 1 => "10111101010101111101010110101010", 2 => "10111100100011100010110000010011", 3 => "10111101110100100010001100011000", 
    4 => "00111110110101101011100000110000", 5 => "00111101101111100111000001111110", 6 => "10111110001001110001101101001000", 7 => "10111110011100011111011100001110", 
    8 => "10111101111001010111111000100100", 9 => "10111110010011010010100100010011", 10 => "10111101111101101100000001010001", 11 => "00111100101000100101101101110101", 
    12 => "10111101011100001101101001011110", 13 => "10111101100010001110111001101100", 14 => "00111101101000100101001000000101", 15 => "10111101111100010111011110100111", 
    16 => "00111110110000101011110011111001", 17 => "00111101111100011011111101111011", 18 => "00111101101100010011010010001011", 19 => "00111100110110101100000001000000", 
    20 => "10111101101011011001110101110111", 21 => "00111101100101001010111101001111", 22 => "10111101101000001010100111011111", 23 => "10111101111000100001101001110010", 
    24 => "00111100101000101100001000110111", 25 => "00111100101101000101101011100110", 26 => "10111110100011101000111100101010", 27 => "00111101000110110010010111110110", 
    28 => "00111101111101001001000011100110", 29 => "10111110111010101111010110011001", 30 => "10111100101101100000010010011111", 31 => "10111101000101111011000011110111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

