-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_3_3_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_3_3_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101011111110010010111100101", 1 => "00111101110100101010111110011011", 2 => "00111101000001100001001100001010", 3 => "10111101000101011010100011011111", 
    4 => "10111101111100111010011100010001", 5 => "10111100000100111110010111111011", 6 => "10111101011110001110100011101010", 7 => "10111101100011100000101100001011", 
    8 => "00111110000010011010010100100010", 9 => "10111101110001101010111111001101", 10 => "10111100101000001110111010001101", 11 => "00111100001000111001100000100000", 
    12 => "10111110001010111010000000011111", 13 => "00111110000111111110111000101101", 14 => "10111100010001101001111110001100", 15 => "00111100000010001001110000011011", 
    16 => "10111110100011000011100011010010", 17 => "10111101001100011111001001010110", 18 => "00111100110101110101100111101111", 19 => "10111101010111001000010000110000", 
    20 => "10111101110001110011001011011111", 21 => "00111101011000010110100100111100", 22 => "00111101100010011011110110000100", 23 => "10111101110001011001101110000000", 
    24 => "10111101111000100100111111101100", 25 => "00111101111010110111000100110010", 26 => "10111100111110111011111110010100", 27 => "00111110010010100101011110101000", 
    28 => "10111101111101111101101101101110", 29 => "00111101000001101101000011010101", 30 => "10111100011100100000011001000010", 31 => "00111110000011010101100001000011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

