-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_25_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_25_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101010111110010100110010001", 1 => "10111101100011011111100100111000", 2 => "10111110111011001010111101110001", 3 => "00111101101011010010101110110010", 
    4 => "00111111000001010101111101100111", 5 => "00111010110011110101101100011101", 6 => "10111110110001001011010101111000", 7 => "10111110100010111011111011101100", 
    8 => "10111101100100000110000101000001", 9 => "00111101101100100000111000011111", 10 => "10111101001010011000011001110111", 11 => "00111100101111101010010011101100", 
    12 => "00111100111111110111010110010111", 13 => "10111100010111100100110001010001", 14 => "10111100101001000101111101011011", 15 => "00111101011101000100000010101111", 
    16 => "00111110011000110100010100000111", 17 => "10111101001010100011000101100010", 18 => "10111101110001001011001100111110", 19 => "00111101011111101111111000001101", 
    20 => "00111101100000000001111101110101", 21 => "10111101111100010011001101111111", 22 => "10111101110100000100110011001111", 23 => "10111100000000100010111111110001", 
    24 => "00111101101010111001011101111000", 25 => "10111101101001011001110010001101", 26 => "00111110001100101111000100100100", 27 => "10111110000111010001100010001111", 
    28 => "10111101111001100000101000100000", 29 => "00111110101110111000000110010101", 30 => "00111101001011111101111111000010", 31 => "10111101110010111100111110010010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

