-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_57_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_57_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101110001001110110001100011", 1 => "10111100111101111101111110100000", 2 => "00111100000000001001110101001001", 3 => "00111101101010110010111010011101", 
    4 => "10111101101000010111001100110010", 5 => "10111101100011001010110011010010", 6 => "00111011111101111110110000110101", 7 => "00111101100111100010110011011100", 
    8 => "00111101110101011101001011010000", 9 => "10111111010100101100111001010111", 10 => "10111101101100101001101110101110", 11 => "00111100100000100010100110100110", 
    12 => "10111101110011010010100110011001", 13 => "10111110000000100010010101110100", 14 => "00111110010000100010001101011011", 15 => "00111101101000010100000111101010", 
    16 => "10111101101010101011000101001111", 17 => "10111101000101101001100011111110", 18 => "00111101110110001011010100000011", 19 => "10111110111011001000100001000000", 
    20 => "00111101010010001100100100110010", 21 => "10111011101101110100010101111100", 22 => "00111101101011110011000010100101", 23 => "10111101100110001010111111000100", 
    24 => "10111101100111010010010100100100", 25 => "00111100110100011111000111010000", 26 => "00111101010001000010100001001110", 27 => "00111110001000110110110111101100", 
    28 => "10111101110000000011001101100001", 29 => "10111101100010001011100101111000", 30 => "00111101110111001011100000010111", 31 => "10111101110110110000110001000110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

