-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_57_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_57_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111100000100100111100100010100", 1 => "00111110100001011101011001011010", 2 => "00111110011011001110011001111101", 3 => "00111011111000110110000010001101", 
    4 => "10111110010000000000110110100010", 5 => "00111101101001001010111010000110", 6 => "00111110010101110111110000000011", 7 => "10111110000010110011110101001011", 
    8 => "10111110011101111011001010001001", 9 => "10111101101011001011110110011000", 10 => "00111110010100010110110101101110", 11 => "10111100100010011110100110001110", 
    12 => "00111101110100010001000101101011", 13 => "10111101101010101111001101011110", 14 => "00111110011101101001100010111011", 15 => "00111110000110010010010001101100", 
    16 => "00111110010010001010001100101111", 17 => "10111110100011010010111010010100", 18 => "10111110000110001110001111101111", 19 => "10111101111011001010000000111100", 
    20 => "00111110110101010111000001100001", 21 => "10111100001111110011001110000111", 22 => "00111101110001010111010100111010", 23 => "10111100101100101110100111001101", 
    24 => "10111101110001010111011111011001", 25 => "00111110101100110000000110000110", 26 => "10111110001000000100101011111001", 27 => "00111101010010100100011011100001", 
    28 => "00111110001111100001001001100010", 29 => "00111110011110010011011010000010", 30 => "00111110101010111100000011000010", 31 => "10111110100111111001110111010100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

