-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_45_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_45_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111100110111111101100010101110", 1 => "00111101010001110000000000000100", 2 => "10111100101010100101011000010101", 3 => "10111101101111111100010011000001", 
    4 => "00111101101000011111011001000101", 5 => "10111101101001001100011010100100", 6 => "10111101000101011001101100111101", 7 => "10111011101110010010110000000110", 
    8 => "00111100110000100111111010010101", 9 => "10111101100111000000111000111001", 10 => "10111101110100111100001011011011", 11 => "00111100000110101011101100000010", 
    12 => "00111101011101100000001010000110", 13 => "00111101001100001001001100010000", 14 => "00111101010010001000110101101101", 15 => "10111110011011101010111000011001", 
    16 => "00111011011010001111101100000001", 17 => "10111100101110111111101101011001", 18 => "10111100100010111011110100111000", 19 => "00111101000111101111100101010101", 
    20 => "10111100100101011110101111111011", 21 => "00111100000001111101011011111001", 22 => "00111101010011001000101111001010", 23 => "10111101100100010010110110111010", 
    24 => "00111101101010001011011001010010", 25 => "00111101011001011011010100110001", 26 => "10111100000010011010110010111101", 27 => "00111101100100110100100110111111", 
    28 => "00111101110101001101101001001101", 29 => "00111100101001100100001111001100", 30 => "00111101111111111011101111011000", 31 => "00111101100101011100010110110101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

