-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_58_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_58_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101011101101101100001101111", 1 => "00111111100100101011010001011011", 2 => "00111101101110110011101001101001", 3 => "00111100110111110010110010110110", 
    4 => "00111101101110010101011110001010", 5 => "10111100000010101010110010010111", 6 => "00111110001000011010000100010010", 7 => "00111101000101011111011110000011", 
    8 => "00111110001010100001110011101111", 9 => "10111110100000010010001100111110", 10 => "00111101100110011110100111010001", 11 => "00111101110011000111110010010101", 
    12 => "00111101100101110100010001110000", 13 => "10111011111111100100011110011001", 14 => "00111110000100001011110010111110", 15 => "00111110000100101110011100101110", 
    16 => "00111101100001011101100001010001", 17 => "10111100110111101101110100000101", 18 => "10111101100111001101110101010001", 19 => "10111111010110000101001010100100", 
    20 => "10111100000011111011010000111110", 21 => "10111110110101110000101001011111", 22 => "00111101110101100110111110010011", 23 => "10111101110011010000110101001010", 
    24 => "00111110000110100100111001111011", 25 => "10111110101101111000100001110110", 26 => "10111100100111000010111000110100", 27 => "00111111000101000101110000100101", 
    28 => "00111110001111110010000100101101", 29 => "00111101100111110100100010000000", 30 => "00111111000001110011001011001111", 31 => "10111110100010010011011100001001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

