-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_3_18_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_3_18_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111100111001110111011100001000", 1 => "00111110000010010011110111011001", 2 => "00111101010001100111110111111110", 3 => "00111101100111010110111110010111", 
    4 => "00111101010100001101111000001001", 5 => "10111100111111111010000110100001", 6 => "00111101011100010100111011000010", 7 => "10111101011101011001100010011110", 
    8 => "00111110001000100010111110101101", 9 => "00111101010001101011100111000011", 10 => "10111101110010110000111110101110", 11 => "00111101100001100011010110100100", 
    12 => "00111110000000100010011000111110", 13 => "00111101100101011000000100000110", 14 => "00111110000011011101001100110101", 15 => "00111011111101110100110011010011", 
    16 => "10111100111010011110010111100010", 17 => "00111101100101011110001110010111", 18 => "00111100001100011000000100010111", 19 => "10111101001011000001110000011101", 
    20 => "00111101101010110000011000111110", 21 => "10111101001110011100110110000001", 22 => "00111011100101010101101101000110", 23 => "10111101101001001000111110010111", 
    24 => "00111101101010110100011000110101", 25 => "00111110010011011000110001101101", 26 => "10111100011010010010010011110010", 27 => "00111110001010010101101110111100", 
    28 => "10111010001100001111001001111100", 29 => "00111101001011101101010101101011", 30 => "00111101100101100100100111010100", 31 => "00111101101110011110111010001001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

