-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_59_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_59_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101110001010001000000001010", 1 => "10111101111000110000001100111010", 2 => "00111101110001010010011000001111", 3 => "00111100100001100010001011000100", 
    4 => "00111110010010111100000000011010", 5 => "10111101011011101100110100001000", 6 => "00111101011011010000110101001010", 7 => "10111100111011101111110000110111", 
    8 => "00111100010110101100111011101110", 9 => "10111100101100001010010011100011", 10 => "00111101000100001100011011111000", 11 => "10111101110110000101110101110100", 
    12 => "00111101000011111111010101000001", 13 => "00111100101100001100011001110001", 14 => "00111110000010110100001001000110", 15 => "00111110010000101000111101011100", 
    16 => "00111110110000010000011011001101", 17 => "10111101100001001101101110011100", 18 => "10111101110001101010111000111010", 19 => "00111101111111001111110011000110", 
    20 => "00111101111010000100000101101000", 21 => "00111110011000101111000000010111", 22 => "10111101101100001100000110111001", 23 => "00111101111001010001001110110110", 
    24 => "00111110001001111100100111011110", 25 => "00111110001100001111110101111110", 26 => "00111101110101101000010000000110", 27 => "00111101011000111000001100100111", 
    28 => "00111101110100101010100011001010", 29 => "00111100010011010000011110000101", 30 => "10111101010001110010011111011101", 31 => "00111100100110001000000010010101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

