-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_17_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_17_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101110010110101000010110001", 1 => "00111101001101010100000110010110", 2 => "00111101010001101100000000001110", 3 => "00111110010000011111110110011100", 
    4 => "00111110001110110001110101010000", 5 => "10111101000100011100111000101001", 6 => "00111100010111101100010111110100", 7 => "10111100001100111001000110010010", 
    8 => "00111101011110101111100001011001", 9 => "00111101111010000101101010010010", 10 => "00111101011000010110000011011001", 11 => "10111100010100110001111111001101", 
    12 => "00111101100001110111000010111101", 13 => "00111100100101101000100101000100", 14 => "10111100000110010010100001011011", 15 => "00111110001010001010000011010011", 
    16 => "00111101001100100000110110011001", 17 => "10111101000000100011101101111001", 18 => "00111101011010111110110011101110", 19 => "00111110000010011001010010011111", 
    20 => "00111100110001110100010100111001", 21 => "10111101100111110111101111100001", 22 => "00111101101101011110111100100000", 23 => "00111110000111010101010000010001", 
    24 => "00111101100011101101000110111111", 25 => "00111101101100110001111011000001", 26 => "10111101011101001101001101111100", 27 => "10111101101011001101110010000111", 
    28 => "00111110010100001011010011100001", 29 => "00111101010111000000111111001011", 30 => "10111100111110100111110010011110", 31 => "00111101011100010110111000110111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

