-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_1_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_1_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101011110001100000000000101", 1 => "10111110000011100101000100001001", 2 => "10111101100111000110010101000001", 3 => "10111101100011110110110001101010", 
    4 => "10111100010111100110100110101101", 5 => "10111101001101110100001101100011", 6 => "00111100100101110100001111101001", 7 => "00111101001000101011110011111001", 
    8 => "10111011100100101111111101001100", 9 => "10111101101010010010001001010011", 10 => "10111101101000010111011101100100", 11 => "10111101110110000100101100011011", 
    12 => "00111011111011011100001110111101", 13 => "00111100101111000000110000100000", 14 => "10111101011110101010101011000001", 15 => "00111101011101001100110000100101", 
    16 => "00111101000100100000011111010101", 17 => "10111101010010110111001111010010", 18 => "10111100010100100110011101000001", 19 => "10111101111101011101010101101111", 
    20 => "10111011111111110011101011011110", 21 => "10111100010101000100100110011001", 22 => "10111101110110110111010010011011", 23 => "00111101101010101011001011100001", 
    24 => "10111101100001001100000101100110", 25 => "00111101100011111110100110111000", 26 => "10111101101000101001111000001010", 27 => "10111011100111000100010101000110", 
    28 => "00111101100100101011000010100111", 29 => "00111101110111011011111111001111", 30 => "10111011111010101101000011000100", 31 => "10111101001000000000100111110110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

