-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_40_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_40_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110011011101011011000111001", 1 => "00111011110110101010100100101110", 2 => "00111100110101100110011010101010", 3 => "10111101101101110111111000011100", 
    4 => "10111101100101111011000011110111", 5 => "00111101000001000010001000000011", 6 => "10111100010011000111000010000110", 7 => "00111101100100001011100111011100", 
    8 => "00111100100110101000011010010100", 9 => "10111101110011100011110011011010", 10 => "10111101100101001001011010101011", 11 => "00111011111011001111001000000110", 
    12 => "00111101100010010001010100111000", 13 => "00111101100101011010001010010100", 14 => "00111101011010001001110110101110", 15 => "10111011000000001000010000011111", 
    16 => "10111101001110000011000101101010", 17 => "00111101010110011000101011101100", 18 => "10111101100001000011000100111000", 19 => "00111100100000110110110010011100", 
    20 => "00111101011101010001110011100011", 21 => "00111100101110011010100111011010", 22 => "00111101000000011111101110000011", 23 => "10111100110110100011110000100001", 
    24 => "00111011110000011110001101100101", 25 => "00111100010110011010110110000110", 26 => "00111101100111010010010110101011", 27 => "10111101000110101000001001100010", 
    28 => "00111101111011011100000000010010", 29 => "10111011111101001000110000101110", 30 => "10111101000010000011011101110010", 31 => "00111101011000010101010001000011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

