-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2B2_0_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2B2_0_ROM_AUTO_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110001100111010100001100001", 1 => "10111110010101100001011100111100", 2 => "10111101101111001011010001101100", 3 => "00111110101100001111011110111010", 
    4 => "10111101000001101101111110000011", 5 => "00111111011110101111011110010000", 6 => "00111110001001001000010000001110", 7 => "00111110001001001011001000110001", 
    8 => "00111110101001011100101011010001", 9 => "10111111010001001110001010100000", 10 => "00111101100110001000110100101010", 11 => "10111101110110110000110111011000", 
    12 => "00111111101001100010111101000000", 13 => "00111110010000010100001011110110", 14 => "00111101101010011110100100001000", 15 => "00111111000110000001100111100011", 
    16 => "00111100110111101001111000011011", 17 => "10111101101011101010101101111010", 18 => "00111111000001000000101000111001", 19 => "10111101110010011101010100011011", 
    20 => "00111101100100011101110111100011", 21 => "00111110011100111110010100110010", 22 => "00111110010000000110111101101001", 23 => "10111101011110100010100111000111", 
    24 => "10111111100000110010000100110110", 25 => "00111101001011110100001001111000", 26 => "00111100010001011011010010101011", 27 => "10111101101010111000101001011101", 
    28 => "10111101001101111100111111100110", 29 => "00111110011101001001000011100110", 30 => "10111110111111001100111111110010", 31 => "00111100011110100110100110111110", 
    32 => "00111101010111010001111001010100", 33 => "10111110101100101110110001101100", 34 => "00111100101011000110011010010000", 35 => "00111101010001110011111111111011", 
    36 => "00111110001010011101111111011011", 37 => "10111100100100110101111111000100", 38 => "10111101010101101111001000011111", 39 => "00111110010111110100000011100110", 
    40 => "10111110000101010010111001110011", 41 => "00111110101011101011110101101111", 42 => "10111111101001110101110111001100", 43 => "10111101101001010010010100000011", 
    44 => "00111110100010010110010001000001", 45 => "00111110100111001110100010111000", 46 => "00111110101000101111001100011011", 47 => "10111110000001110000001110110000", 
    48 => "00111101010011101000111110110000", 49 => "10111100010000111011110101011010", 50 => "10111100011111010110000011101001", 51 => "10111101011110000111110011101001", 
    52 => "10111101000001101000011001100010", 53 => "10111110101001111101001100101100", 54 => "10111100010100110100000101011011", 55 => "00111101101110110001111000011001", 
    56 => "10111101101100111100000000111100", 57 => "10111110100100101100110001001111", 58 => "10111110100111101011000110100011", 59 => "10111111001011001001100111010000", 
    60 => "10111101100101100111001010111001", 61 => "10111101110101001111111100000000", 62 => "10111101011111101111010110101001", 63 => "10111101110000010101010011001010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;

end if;
end process;

end rtl;

