-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_106_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_106_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110110111010001100101011001", 1 => "00111010100100001101010110100110", 2 => "10111111100111010001100011001010", 3 => "00111101110101100100000011101010", 
    4 => "10111111001010010010001000100001", 5 => "10111101100010110010110110010000", 6 => "00111110010101001001110101111100", 7 => "00111101110011000110001101101011", 
    8 => "00111110010011001001000110001110", 9 => "00111110101010010010101010110111", 10 => "10111101110000111100010010110001", 11 => "10111100111111001000011011001111", 
    12 => "10111110111101111111111011110100", 13 => "10111101101010101110100111101110", 14 => "10111110010000001101010110100110", 15 => "10111101101100101110001001110110", 
    16 => "10111110001000000010100010100010", 17 => "10111101000100110010110101101111", 18 => "10111101011100001001110110001100", 19 => "00111100100001100010101100101000", 
    20 => "00111110000001010000110101101011", 21 => "10111100010110100001101010010011", 22 => "10111101001011011011101001001101", 23 => "00111110001111110110001010110111", 
    24 => "10111110000111110111110000100100", 25 => "00111110000000011110000110001111", 26 => "00111101001011011100011111101111", 27 => "00111101000011010101111010001101", 
    28 => "00111101011000100010000111001001", 29 => "10111101100111110111011010100011", 30 => "10111101000111011101101100010010", 31 => "00111011011101110100010001110000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

