-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_93_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_93_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101001111100110101101000000", 1 => "10111101011111111111100110110101", 2 => "10111101011101011001001001010011", 3 => "00111100010111111100010111001110", 
    4 => "00111100000100010011000111101100", 5 => "00111101100110100010100111000111", 6 => "00111011100011010110010011011000", 7 => "00111100101100011101000011001000", 
    8 => "00111100011111001000011011001111", 9 => "10111101100101111011101111111001", 10 => "00111011110100100110011101000001", 11 => "00111011110101110101100111101111", 
    12 => "00111100001000101110011111110111", 13 => "10111101000011110010111000000110", 14 => "00111101100000001111101100100010", 15 => "00111011110110100000100111001100", 
    16 => "10111101000011010101110110000001", 17 => "10111100110111100011110110100011", 18 => "10111101101010001100011010010011", 19 => "10111100110110110111110011111110", 
    20 => "00111010111100000110001011010100", 21 => "00111101101101000000010011101010", 22 => "10111101010011010101000011101100", 23 => "00111101001110100001101100011001", 
    24 => "10111101100111011010001011111001", 25 => "10111101100101000001110010000010", 26 => "00111100111001100111111110010001", 27 => "00111101100011111111101110001011", 
    28 => "00111100010110001110010000110010", 29 => "00111100111111011110100100111010", 30 => "00111101100110100001000100100011", 31 => "00111101001111110100001101000010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

