-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_3_42_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_3_42_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101101101000011001010000111", 1 => "10111011100100100101011110000110", 2 => "10111101111100001000001011001111", 3 => "10111110000010010001000011000011", 
    4 => "00111011101100011101110101011101", 5 => "10111101000101010111111111111010", 6 => "10111100110100101110011100101110", 7 => "10111100001010011110001010111101", 
    8 => "10111101001010111001000110110100", 9 => "00111101111101111100111001010011", 10 => "10111100011110000010011011101110", 11 => "10111011101100010010110100110100", 
    12 => "00111101101010001010000101011010", 13 => "00111101010001100111100011000000", 14 => "10111101011001100111110101111000", 15 => "10111101101001101000111000111111", 
    16 => "10111101110101000011101111110111", 17 => "00111101000001100010001011000100", 18 => "00111101110111001011111111110100", 19 => "00111101000001110101100000011001", 
    20 => "00111101100010000010101111101001", 21 => "10111101100110011100111000000111", 22 => "10111110000010010110000010110111", 23 => "00111100011000000101000000110111", 
    24 => "00111100100110101011100011101001", 25 => "10111101010000010011010101010100", 26 => "10111100101110011111000100101000", 27 => "10111100011110010110000110000000", 
    28 => "00111101110011111100011110100100", 29 => "00111101000101100001001011000111", 30 => "10111101100000100010010101110100", 31 => "00111100010110001110000000000001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

