-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_3_29_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_3_29_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110001000101111110000100110", 1 => "00111110010011001110011101000111", 2 => "00111110001101111101011010110110", 3 => "10111100001000010111101100001111", 
    4 => "10111101111110111010100100001001", 5 => "10111101010010100100111101000100", 6 => "00111110001001110101001011011011", 7 => "10111101000010101000011011010111", 
    8 => "10111101011111110000110111000111", 9 => "10111101111010010010011110010001", 10 => "00111101110001111011010101101100", 11 => "00111100100010100010000000010100", 
    12 => "00111110010001101101101110010100", 13 => "00111100000101000101011100111010", 14 => "00111101011010100110001110110111", 15 => "10111101111001110101100110101011", 
    16 => "10111101010001101110100011110011", 17 => "10111101001011001110101110111100", 18 => "00111101101000101011011000101000", 19 => "00111101111010111110000111101011", 
    20 => "00111110010110011111001010111011", 21 => "10111101111011010010110101000101", 22 => "00111101111011000110111011110100", 23 => "00111101101011110011101110100111", 
    24 => "00111110000100101100111000000011", 25 => "00111011001000001100001010000011", 26 => "00111101111100110101010000111011", 27 => "00111011010011101111011001110011", 
    28 => "00111101101000011110101111001000", 29 => "00111101011100000101010000100110", 30 => "00111100000010111101101010010100", 31 => "00111101101000100001111100101010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

