-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_68_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_68_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101011111100111111100101100", 1 => "10111100100011111101011111100100", 2 => "00111101101001011101010000100000", 3 => "00111101100011000010100100111001", 
    4 => "00111101001011100001101011000101", 5 => "10111101100111110101000111110000", 6 => "10111101000110011001001001000011", 7 => "00111101100111111011011110100110", 
    8 => "00111010100001101001110001100111", 9 => "10111101100111000111100000100001", 10 => "00111010101111011100101011010001", 11 => "10111101101010100101110111110010", 
    12 => "00111100111010000110111001111110", 13 => "00111101010101011111000000101100", 14 => "10111100111000110011101011001101", 15 => "10111101000111000010010111010000", 
    16 => "10111011001100101110100111001101", 17 => "00111100110001111001001011010001", 18 => "10111101001000001111001111001011", 19 => "00111101100101111101101011101000", 
    20 => "00111101101000000110001000001011", 21 => "10111101000011100110111000100010", 22 => "00111101001100101111001100111101", 23 => "10111010000111001100001100011010", 
    24 => "10111101100100100110111100011110", 25 => "00111101011111000001101011001110", 26 => "00111101100001011010110011001101", 27 => "10111101100001001001001111001001", 
    28 => "00111100001001101001101111100001", 29 => "10111101100101010001011000010010", 30 => "00111101011011001111010100101100", 31 => "00111101011001100101010010010011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

