-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_0_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_0_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101001100101010011010110001", 1 => "00111100101000001011111001010001", 2 => "00111100110011010011001110001111", 3 => "00111101111110010001011010000111", 
    4 => "10111101111111101100111111101010", 5 => "00111101111011011101110101101110", 6 => "10111100001011110100011010101010", 7 => "10111101101011010101110001110100", 
    8 => "00111101001001101110111010110111", 9 => "10111101110111011001100110001001", 10 => "00111101101011001100111001011111", 11 => "10111100110101000100010101100111", 
    12 => "10111101100010100011100100111111", 13 => "10111010111000001010100001001100", 14 => "00111100000010100010101010010001", 15 => "10111101101001011111110100000101", 
    16 => "00111101110110011101001111001100", 17 => "00111011110010001010001101110010", 18 => "00111101100011011100110000100001", 19 => "00111101001010110000111110101110", 
    20 => "00111101110000011010110101100100", 21 => "10111101110110010101010111111000", 22 => "00111101110001011100000000110011", 23 => "00111100011101000100010011100001", 
    24 => "10111101100100010111011000010100", 25 => "00111101001111000100101100001010", 26 => "10111101101101000001110100001000", 27 => "00111101111101011110011101000011", 
    28 => "10111101111011011100010101010000", 29 => "00111100101000001100101011100110", 30 => "00111100101011011101101111011011", 31 => "10111101001111010011101100101010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

