-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_0_37_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_0_37_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111100100110010011011100001001", 1 => "10111110000001110100011110010101", 2 => "10111101110111100101110100011000", 3 => "00111101110010010100011110001101", 
    4 => "00111110000010000010010000001011", 5 => "00111101001101000110111011010010", 6 => "10111110110100000111101101010111", 7 => "10111010100111111000001110111110", 
    8 => "10111101000011000011110100100101", 9 => "00111101101110000100110100110100", 10 => "00111101001010101010001010100001", 11 => "00111100001001001111110010100100", 
    12 => "00111101001001100011110001110101", 13 => "10111101011110111001110011111010", 14 => "00111101000100001111100001000000", 15 => "00111101011011100011100000100010", 
    16 => "10111110000110011001110110001000", 17 => "10111100100101100010101011100101", 18 => "10111111000000111100101111010101", 19 => "00111101000100000010011010001001", 
    20 => "10111110000101011111001000000010", 21 => "00111111000010100010110001100111", 22 => "00111100110101100100010100011100", 23 => "00111101100101000110100110010100", 
    24 => "00111100110001001110010100001100", 25 => "00111101001001100100111101010101", 26 => "10111101001101110110000010111111", 27 => "00111101011000110101110001011011", 
    28 => "10111101111111010011000100110011", 29 => "10111110111011011100000101000000", 30 => "10111101110100001101001110001101", 31 => "00111100111000000011001011011011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

