-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_27_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_27_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110100000101101000110001101", 1 => "10111101001011001110011110001010", 2 => "00111101000110101101111010101001", 3 => "00111101100100011110001100100010", 
    4 => "00111110000011011000000110101110", 5 => "00111101111010010110000111000011", 6 => "10111100010001110010010111000100", 7 => "00111101011010100101011100100001", 
    8 => "00111110000111110010101111101101", 9 => "10111101001100000101001100011010", 10 => "00111101101000011000110001011101", 11 => "10111101010110011011100000000010", 
    12 => "10111100111001101100011011011110", 13 => "10111011000010000010111100001110", 14 => "10111101011110010111000100111011", 15 => "10111101000001111111011101111011", 
    16 => "10111101100111010011000100110011", 17 => "00111101100100001001011101000010", 18 => "00111100001111001101111111110000", 19 => "10111101100010000100100000111000", 
    20 => "00111101010110101011010111000100", 21 => "10111000111100110100010100000111", 22 => "10111101011111110010010011011001", 23 => "10111101110100011011000101010011", 
    24 => "00111100100011010111000101101101", 25 => "00111110000001100101000101101110", 26 => "00111100011111111001011100100100", 27 => "00111101001011000000010100001100", 
    28 => "00111110011000001101000001101000", 29 => "00111101101111110010110000110000", 30 => "00111110000011001010010101111010", 31 => "00111101110010011000010001011110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

