-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_20_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_20_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101001111000101010110000110", 1 => "10111100001100110000111110001100", 2 => "00111100100000101100100100001000", 3 => "00111101010010110110010100100011", 
    4 => "00111011011000100000100010011110", 5 => "00111101001011100011000011001011", 6 => "00111100000010100111000111011110", 7 => "10111011010001001011110100110100", 
    8 => "10111101000111000010101000000010", 9 => "00111101011101011011000111001000", 10 => "00111100000101110100011000000010", 11 => "00111101101100011010101100001000", 
    12 => "10111101000111111100000010010000", 13 => "00111101100110000111010110010010", 14 => "10111101101110010110010110110010", 15 => "00111100010101010111111111111010", 
    16 => "00111100010110010011110001000111", 17 => "10111101011100001010011011111100", 18 => "10111100111100001111011110111010", 19 => "00111101010100110001000100011111", 
    20 => "10111100100110000100001111000100", 21 => "10111101101000010000100000111110", 22 => "00111101100100010111110001011111", 23 => "00111101011010010000100010100010", 
    24 => "00111011110100000100111001100010", 25 => "00111100100001011101000011111010", 26 => "00111101011111101000100110101001", 27 => "00111100101101100110111110010011", 
    28 => "10111101010011100101011000000100", 29 => "00111011111011001101000001111000", 30 => "00111101011111010011000010101101", 31 => "00111100011000110100101110010100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

