-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_97_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_97_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101000111110100011011101101", 1 => "00111101000111000110010010111011", 2 => "00111101110101100100011100110100", 3 => "10111100001010001111001110101010", 
    4 => "00111010011011000111010000110010", 5 => "00111100101010001101010000110101", 6 => "10111100110101101010001101111011", 7 => "00111010110000010001000110101110", 
    8 => "00111011111001110001010001110111", 9 => "10111101101100110001000110100101", 10 => "10111100111001110011001111101100", 11 => "10111101100000101010110000110010", 
    12 => "00111110001010110101011001110101", 13 => "00111101001000100110101000100011", 14 => "00111101000011011001111110010000", 15 => "00111110100111100101001100100010", 
    16 => "10111100100010000100000111101110", 17 => "00111101110000101100011001101001", 18 => "00111100000011001011100011100001", 19 => "10111101001010101111011010000011", 
    20 => "10111100101010101011001001011011", 21 => "00111100100111100100111101110110", 22 => "00111101111001010111111010101010", 23 => "10111101110110000111010100001100", 
    24 => "10111101010110110100111111101000", 25 => "00111101001000111100111110110011", 26 => "10111101001010011011110011111101", 27 => "10111101000111111010111010111100", 
    28 => "00111101000100000011101110000010", 29 => "10111101010100110110100100110100", 30 => "00111101100000110001010100001110", 31 => "10111101000000110011001011110000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

