-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_0_23_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_0_23_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101101111010111111111011000", 1 => "10111101000010000111101110011010", 2 => "10111101111001011001000110001010", 3 => "00111101111001111000111110101100", 
    4 => "00111101111000001011010101100111", 5 => "10111101100111100011100111110111", 6 => "00111110010101010100110110100101", 7 => "00111101001110011011110111000111", 
    8 => "00111101101001110011011010001011", 9 => "00111101101000000111000010111001", 10 => "00111101010110011000000101111100", 11 => "00111100100010110000010010101011", 
    12 => "10111100010100010110011101100110", 13 => "00111101101111100011101001111110", 14 => "10111100110000001011111111100100", 15 => "00111101110010011001111110100001", 
    16 => "00111110000111110001101000011010", 17 => "10111100011010001100100010101100", 18 => "00111101101110110101100011010001", 19 => "00111110001011011010101100011001", 
    20 => "10111100000010101011100100101100", 21 => "10111101110011011001000111101111", 22 => "00111101010010011111111110010011", 23 => "10111101100100110101111000110001", 
    24 => "10111100110111100000010100000011", 25 => "00111101101100010110111111001010", 26 => "10111101010110010111100000001100", 27 => "10111101110001110110111010100100", 
    28 => "10111101000101010000000100011001", 29 => "10111101001011001000101101000100", 30 => "10111101001110001101011000001010", 31 => "10111101111110010101001001001100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

