-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_38_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_38_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101001010011111000001011111", 1 => "10111101010100110100010110001101", 2 => "00111101100000001111011111111101", 3 => "00111100110000010010101011011000", 
    4 => "00111010000011011101000111100101", 5 => "10111101100011100111000000111011", 6 => "10111101010110100001101010010011", 7 => "00111100101100001101111110011100", 
    8 => "00111100001110110000010111111011", 9 => "10111101100010010111111110100110", 10 => "00111101100101010011111001110000", 11 => "10111100100001101111111011111000", 
    12 => "00111101001100110011101010001010", 13 => "00111101010100111101100101100110", 14 => "10111101101001110011111101110101", 15 => "10111101001010110000011000111110", 
    16 => "10111110000000001110000101110010", 17 => "00111101011001110011010011111000", 18 => "10111011100011111000111001111110", 19 => "10111101100110110010101000101000", 
    20 => "00111011011110111000011011110100", 21 => "10111101101011001000100000011110", 22 => "10111101010011110100011000100100", 23 => "00111100101101011001011110010010", 
    24 => "10111101001011101001101110111111", 25 => "00111100001001100010011001110000", 26 => "00111100011001100011000111111001", 27 => "00111101100100111001011101010111", 
    28 => "00111100011111011000111100001100", 29 => "00111101001110100011100110000010", 30 => "10111101100111101001001100011000", 31 => "00111101101011110011011111111100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

