-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_19_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_19_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101010110110101001100001101", 1 => "00111101100101001101001101111100", 2 => "10111101000110101100000101001100", 3 => "00111101100000010110100010110110", 
    4 => "10111101100111100110101000110011", 5 => "10111011101111111111010001110111", 6 => "00111101011011110010111010001100", 7 => "00111101100110110111101001011111", 
    8 => "00111101101010011111110011110100", 9 => "00111011100101110000011100011000", 10 => "10111101100011010111010110011111", 11 => "10111100000110100110001011101101", 
    12 => "10111011000001111100101001100100", 13 => "00111100011011111100011110100100", 14 => "10111101011000100011010010101000", 15 => "10111101011001011010100110101000", 
    16 => "10111101011000001111010011011000", 17 => "10111101011011110111101000001011", 18 => "10111100110001001010101001010100", 19 => "10111101000001000101110010111100", 
    20 => "10111101000001001110001011110011", 21 => "00111101011011010001010010100001", 22 => "10111100110010010010001101100000", 23 => "00111100111100010101010000000000", 
    24 => "00111101001111111000110010101000", 25 => "10111100110000111100011111010110", 26 => "00111010011010001100100010101100", 27 => "10111101010011001001100101101011", 
    28 => "10111101010011111001010111010101", 29 => "10111101011111010000111000010011", 30 => "10111101100101000010100000001011", 31 => "00111101101010000000111000000110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

