-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_44_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_44_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101101000010111101110010110", 1 => "00111100001000010100110011101100", 2 => "00111100110110010100101011110101", 3 => "00111011101001111101111011010111", 
    4 => "00111110000000001100100011001101", 5 => "10111101101000000110010010101010", 6 => "00111110010110011000000011110101", 7 => "10111101101101110010011110011010", 
    8 => "00111101100001110001101101001000", 9 => "10111101100100001011100011010000", 10 => "10111101111110100001000100100011", 11 => "00111101110000010101001000101010", 
    12 => "10111101111011000111011101010111", 13 => "10111100100110011110101101100100", 14 => "10111101100100001001010000011101", 15 => "00111101001110111110111011000100", 
    16 => "00111110011101100110011101110011", 17 => "00111100110001010001011101100001", 18 => "10111101110111010001110011000001", 19 => "10111100111101111101001100001011", 
    20 => "00111110000101101011110110110010", 21 => "10111110010011110011011011110000", 22 => "00111101011110011000011000110100", 23 => "10111101111010000101001100111011", 
    24 => "00111100110001000100011111000011", 25 => "00111101110100111101011111010100", 26 => "10111101101010010110111101100101", 27 => "00111101001110100011111011000000", 
    28 => "10111101110001101000101110100000", 29 => "10111101000010011100010111100111", 30 => "10111010000111010000011000110110", 31 => "10111110000111111010001000100111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

