-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_0_51_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_0_51_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101111000000010001010011010", 1 => "10111101111101111010101000100110", 2 => "10111100111000010111010111010001", 3 => "00111101110010001010101001000011", 
    4 => "10111100100101100111110010101111", 5 => "10111101011000001101100110010100", 6 => "10111100100010011011001100000111", 7 => "00111100110011110101111101001110", 
    8 => "00111001110100100011110101001111", 9 => "10111101110110001001111110000100", 10 => "00111101011011001000000011000111", 11 => "10111100100010111100010110011100", 
    12 => "00111101101010100101111001111000", 13 => "10111100111011010001001110010100", 14 => "10111101010101110111110110010101", 15 => "10111101100000010101011011100010", 
    16 => "00111101010101101100000111100011", 17 => "10111101100110111101100000111000", 18 => "00111101011101111000110011001010", 19 => "10111101100000011111100011100100", 
    20 => "00111100000000001011011001110100", 21 => "10111101000010101101000000111110", 22 => "10111101110001011001010010101111", 23 => "00111101011011111111001110101110", 
    24 => "00111101101001001000000111110101", 25 => "00111100100110010111100000001100", 26 => "00111101110111111110001010100100", 27 => "00111101100001001110111100000011", 
    28 => "00111101001010000010010100011000", 29 => "00111101001100110101010111001110", 30 => "10111101011100100000011101001111", 31 => "00111101101111001110011101000111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

