[hls]
relative_roots=C:/OCDS/OCDS_4K_Streams/OCDS_4K_Stream
# Inferred from performance & pipeline pragmas/directives
syn.directive.array_partition=cloud_mlp_top/B2 dim=1 type=cyclic factor=2 variable=B2


