-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_0_27_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_0_27_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110000010100010100000110101", 1 => "10111101010100001101000001101000", 2 => "10111001101111011100101011010001", 3 => "00111110001010001000000010010101", 
    4 => "00111101101000011011001000011100", 5 => "10111011000110001100001110110001", 6 => "00111101101111011010101011010110", 7 => "00111101110111101000100100100010", 
    8 => "00111101111001100001100111011011", 9 => "00111101000111001001011100001111", 10 => "00111110001010010101111110101011", 11 => "00111100010010000111100110000001", 
    12 => "10111100011111011100110111110111", 13 => "00111110010000000010110001001101", 14 => "00111101000101110010110111100100", 15 => "10111101101010011101111100010001", 
    16 => "00111100100001111110001110001111", 17 => "10111100001001011111110001111110", 18 => "00111101101010100001100000110111", 19 => "10111100001111101100101010101100", 
    20 => "10111100001110101110100010011111", 21 => "00111101110101011110111010011010", 22 => "00111101100110001111101000110111", 23 => "00111101101000000101100110100111", 
    24 => "00111110001110001010110101101001", 25 => "10111100110110001110010000110010", 26 => "00111101110111000100001000100000", 27 => "00111100100110000011111110010010", 
    28 => "10111101110101010000010101001011", 29 => "10111101001101000011101001100100", 30 => "10111101111111010011011011111000", 31 => "00111101101100110001101010001111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

