-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_48_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_48_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101110101000101001100001001", 1 => "10111110010100011010110011011110", 2 => "10111110000010000111110000100000", 3 => "00111101100111011000111010000110", 
    4 => "00111110001011000001110100101010", 5 => "00111100010011000010000011010101", 6 => "00111110100000100110111100111111", 7 => "00111110001011001100111101101100", 
    8 => "10111101111000110010000110100011", 9 => "10111101111001010111100001100000", 10 => "10111100101111000000111000111001", 11 => "00111110010010001000011100100011", 
    12 => "10111111010011111110101011110111", 13 => "10111101011000011101001000011000", 14 => "00111101000111001011101111000011", 15 => "10111111000010110000101011000100", 
    16 => "00111101001111100110110101011001", 17 => "00111110010001010110100000011111", 18 => "10111101100000011101011101010110", 19 => "10111110000010000110101010010000", 
    20 => "10111111011111111011110111100000", 21 => "00111100100001011100011001111110", 22 => "00111101000010000111100001110101", 23 => "10111110000111000100001011101010", 
    24 => "00111110001010011010010111101100", 25 => "10111110101011001100100100100001", 26 => "00111100011010111001111001001001", 27 => "10111101100011101110011111000101", 
    28 => "10111110001111111011101111011000", 29 => "10111101011010001010000111100000", 30 => "00111110000010001000010011000111", 31 => "10111101101011110111101110011110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

