-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_13_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_13_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111110000001000111111111011100", 1 => "00111101010110111111110111111000", 2 => "00111100110010101111001011011000", 3 => "10111101100101011110101011101110", 
    4 => "00111101101101111001100011011001", 5 => "10111101010001100100011001101011", 6 => "00111100100101010100110010011000", 7 => "10111101111101010101001001011101", 
    8 => "00111100000110111010010111100011", 9 => "00111100000001001011111001000000", 10 => "10111100110101001001111110010101", 11 => "10111101000000110011011100100010", 
    12 => "10111100111101000001011010111110", 13 => "00111101010101110101110100010100", 14 => "00111011101110011111010101011010", 15 => "10111110000001101011000100011100", 
    16 => "10111101111001011111010000011011", 17 => "10111100001000011101111110111001", 18 => "00111101110100010100000110100111", 19 => "10111100111101100111001010111001", 
    20 => "10111101101101010010001110110011", 21 => "00111100000101000101101101101100", 22 => "00111011011111001000001010011101", 23 => "10111100000111011010010110011000", 
    24 => "10111011111100001101100001000101", 25 => "00111101001010111010000101101110", 26 => "10111101100100011011110111101000", 27 => "00111101011111110001011100110111", 
    28 => "10111011100000101001010010011010", 29 => "00111101100100001011100111011100", 30 => "10111101100001101111110001011001", 31 => "10111100111010111001001111001101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

