-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_37_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_37_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101100001000101110000110110", 1 => "00111110011010000011111010000101", 2 => "10111110010010111101110100110011", 3 => "00111110100010111100101011011010", 
    4 => "00111110100101101111011000110000", 5 => "10111101101001111110000001101001", 6 => "00111000110100011011011100010111", 7 => "10111110001101110101011011001001", 
    8 => "00111110010110111000110001110110", 9 => "00111110000011111100001000100010", 10 => "00111100100010110010001000001000", 11 => "00111110111110001101001111110010", 
    12 => "00111110010101001101101111100000", 13 => "00111011110110110101000011110100", 14 => "00111110000000001110101010011110", 15 => "00111110111001110011110101111101", 
    16 => "10111101100000101110001010111001", 17 => "00111110100001110010100101101111", 18 => "10111101001110101111110010001011", 19 => "10111110100100010010001100111110", 
    20 => "10111110110100001011100110011001", 21 => "10111101100000111001100000100000", 22 => "00111110000100111010111101110101", 23 => "10111101010011000111101100000011", 
    24 => "00111101100000110100000000001100", 25 => "00111101101101000110100000000001", 26 => "10111110110100000000001011100010", 27 => "10111101100111100001010000111000", 
    28 => "10111111001100101111101000011110", 29 => "10111100101110111011110001101111", 30 => "10111111000010001011110101110111", 31 => "00111101100100110111100011101110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

