-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_118_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_118_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111110001100001111101100100010", 1 => "10111111001001100110000111110010", 2 => "10111110110011100100110001010001", 3 => "00111101011100010100001100111001", 
    4 => "10111110011000000111100101011111", 5 => "00111101100001111011001101010011", 6 => "00111100101011010100110101000000", 7 => "10111101101001010110110101011101", 
    8 => "00111101100110111100101010010111", 9 => "00111110000110101010100001100101", 10 => "10111100011000101101000111110010", 11 => "10111101001111001001001101100100", 
    12 => "10111110101001011001101100111101", 13 => "10111101011010011011001110001101", 14 => "00111101101101011011011010000000", 15 => "10111110000101011000011011001011", 
    16 => "10111110001011101111010100100011", 17 => "10111110001110010000011111011001", 18 => "10111110000001101101000110011110", 19 => "00111100110011111100110001011100", 
    20 => "10111110100010001011111101111111", 21 => "10111101101011111100011010010111", 22 => "00111101110010100111111011111010", 23 => "00111101110100111000110101100001", 
    24 => "10111010001011111110011000001100", 25 => "00111100110110000000011111111111", 26 => "00111101110011111001010101001111", 27 => "10111101111110000100100110001000", 
    28 => "10111110000001011000111000100010", 29 => "10111101100111110110000010011110", 30 => "00111101010110000010000000011101", 31 => "10111110000100110001001110111110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

