-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_0_63_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_0_63_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101101110100010110001100111", 1 => "00111101110001110110000001111100", 2 => "00111100110110111001111010001100", 3 => "10111101000001000111110100111101", 
    4 => "10111101011101011111010111110001", 5 => "10111110010110000101010100010001", 6 => "00111110100011000011011110000010", 7 => "10111101011010001100001001100001", 
    8 => "10111100100000110101110111101110", 9 => "00111101111011110000100001000110", 10 => "00111101100000111001000011001001", 11 => "10111101111001001000101011011111", 
    12 => "00111110110110001110010100111111", 13 => "10111011101110010100110110010100", 14 => "10111110000101010111101101000010", 15 => "00111110100101110101110000101001", 
    16 => "10111101100010000100110111111101", 17 => "10111101111001101111100010101101", 18 => "10111110001001011101100100011011", 19 => "10111110001100010111011010011011", 
    20 => "10111110110011010111000100101010", 21 => "10111101110100011010001100101011", 22 => "10111100110110001110111010101111", 23 => "00111100011010011001000111111111", 
    24 => "10111011111001100101001110000111", 25 => "00111101101101111101001010000101", 26 => "00111101100001010001011001010101", 27 => "10111101011011111111100111111000", 
    28 => "00111101110000101000111111100010", 29 => "10111110110000111110101011110111", 30 => "10111100111101100110110001101110", 31 => "10111101011010000001011001101010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

