-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_102_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_102_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101100110001010111010111000", 1 => "10111010110101000101011000101110", 2 => "00111100111110100011101110011011", 3 => "00111101101011111110000001001000", 
    4 => "10111011101101100101101010011011", 5 => "10111100101101000010100010010001", 6 => "00111101100110010111001011001101", 7 => "00111101100111000010010111010000", 
    8 => "10111101101011111000001001101111", 9 => "00111100110001011010101000101110", 10 => "00111101001011110100111100001110", 11 => "00111011110110010101000101000000", 
    12 => "00111101101001010101110010010110", 13 => "00111011111011100010100001100111", 14 => "10111100100000100010100110100110", 15 => "10111100111001001110111100000011", 
    16 => "00111100011110110011111110100111", 17 => "00111101011111001011111101101110", 18 => "00111011111011101010111010011111", 19 => "10111101101011101101101010101001", 
    20 => "10111101010111110001010110100101", 21 => "10111101100101101100100111000001", 22 => "00111101010101010110100111110101", 23 => "10111101011001100100000110110011", 
    24 => "10111101101100001101100101010001", 25 => "00111100011010000000001110001010", 26 => "10111101100100000111010100101110", 27 => "10111101000010001010010110001011", 
    28 => "10111101000010111101100110001000", 29 => "00111101101101111001101011110010", 30 => "00111101001010001001111111000111", 31 => "00111100100001000111111101010110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

