-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_84_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_84_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110101001010001101100101110", 1 => "00111110001010001100001010100100", 2 => "00111110000110101111000111001100", 3 => "10111101100100100001011100001001", 
    4 => "10111110000110001100000000000101", 5 => "00111011111101011010100101100101", 6 => "10111101000001011110011011111111", 7 => "10111101001011010000000111000001", 
    8 => "00111110010000011001010100000011", 9 => "10111101111111100010011010010001", 10 => "00111010111000010101000000010010", 11 => "10111101101000100000110011010000", 
    12 => "10111110110011110110110111011011", 13 => "00111101000100110111010010111100", 14 => "00111110000111101110001010000110", 15 => "10111101011000110000011001100000", 
    16 => "00111110100000010011011110001111", 17 => "00111110001000111101000011000000", 18 => "00111100001011000010110111110001", 19 => "10111100110000110100010111010000", 
    20 => "10111110000001110110110101010101", 21 => "10111101100011111000100101000000", 22 => "10111101010111111100101100001100", 23 => "00111101110001111011010101101100", 
    24 => "10111100000010100001000101100110", 25 => "00111101000101001110111000111001", 26 => "10111100000100001101010110100110", 27 => "10111101000000000111010001100100", 
    28 => "00111110011110000010111100001110", 29 => "10111101000011001010100100100110", 30 => "10111101001101011101111111101100", 31 => "10111101111000101101010010010001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

