-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_62_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_62_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111100110110100101011101100100", 1 => "00111101100101000001000011111001", 2 => "00111101011001110011110101011100", 3 => "10111100100000000001011100010010", 
    4 => "00111101011101000010100110011110", 5 => "10111100000100011100010010111001", 6 => "00111101100100010000101010011010", 7 => "10111100000001010011011111100011", 
    8 => "00111100000011101001001011010101", 9 => "10111101100111001010101001110110", 10 => "10111011001010101001011100011000", 11 => "00111100010010100011011000011010", 
    12 => "10111100000010010100100000010011", 13 => "10111101000000110001001101111011", 14 => "10111101000000001011010101100111", 15 => "00111101010101010011010110000111", 
    16 => "10111110100000101101011011001011", 17 => "10111101000000100010001101011011", 18 => "10111100101110100110000001001110", 19 => "10111101001000000010000100001000", 
    20 => "00111101100000000100011001000001", 21 => "10111101000010111011110100111000", 22 => "00111100100111011011011001011111", 23 => "10111101001001110100110000001010", 
    24 => "10111101101101001110101100010100", 25 => "00111100111011101111001111010100", 26 => "00111100101000111001100000100000", 27 => "10111100111010100110101000000001", 
    28 => "00111100001100010101011100100110", 29 => "10111101101101011101000000110001", 30 => "00111011111010010000001101100100", 31 => "10111100110011000000001101111001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

