-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_41_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_41_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101010101110011011101010100", 1 => "10111101110110100010101001001110", 2 => "00111110000000101110000111101111", 3 => "10111100100100011111000011000011", 
    4 => "00111101101010100000110100110101", 5 => "10111110000100100010111101101010", 6 => "00111110000101101001011111110010", 7 => "10111110000011011101011111101101", 
    8 => "10111011110000000010011011001100", 9 => "00111101001000101010101000011001", 10 => "10111101111111010011010001011001", 11 => "00111101010101100110000101101011", 
    12 => "10111100110100101111001111000011", 13 => "10111100111010000110100000110100", 14 => "10111101110011110010110011111001", 15 => "10111110000110001101001110101110", 
    16 => "00111101101111110110110000100111", 17 => "10111101010001111111101010100000", 18 => "10111101000111000010101000000010", 19 => "10111101110000111101111111110100", 
    20 => "00111101100000010001000010100001", 21 => "10111110001000101011000000100001", 22 => "10111100100010001101001010100010", 23 => "10111101110001110111001111100010", 
    24 => "00111101101010010010011100001011", 25 => "00111101011001001100011100101010", 26 => "10111110000010110011100111100010", 27 => "10111101111000001110101101101000", 
    28 => "00111011111011101001110111011000", 29 => "00111101100110011101010101011110", 30 => "10111101010110111010011011110000", 31 => "00111101100100000000001111101111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

