-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_3_22_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_3_22_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101110101111100000100110111", 1 => "00111101001011000010010110001101", 2 => "10111101111100000011001100011110", 3 => "00111101000111010111101110100110", 
    4 => "00111101000001101001101001001110", 5 => "10111011000010010100110001000100", 6 => "10111110000110101000000111011100", 7 => "10111110010110001100110001010111", 
    8 => "00111100110111111111011000001010", 9 => "00111101111000110110000110011001", 10 => "00111101101111101001101011110110", 11 => "10111100001000001111000010100110", 
    12 => "10111101101100000110001111100000", 13 => "10111110010111101001101011110110", 14 => "00111101001000101010111101010111", 15 => "00111101110100101111110100110011", 
    16 => "00111101110011110010100001000001", 17 => "10111101010111000110000110010101", 18 => "10111101111011001111010100101100", 19 => "00111110000101011101100000001110", 
    20 => "00111101000001000011000110111110", 21 => "10111101001010101101001111101001", 22 => "00111100100010111001111111011100", 23 => "10111101110010001001011101100011", 
    24 => "10111100110001111001001011010001", 25 => "10111110010101110110100001011010", 26 => "00111011101001101111110001011001", 27 => "00111101110111111101110101100110", 
    28 => "00111111101110110000110001100111", 29 => "10111101010010101110100001011100", 30 => "00111101111101000011000011110101", 31 => "00111101100111100110011110010100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

