-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_95_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_95_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101010110010011001111100011", 1 => "00111101111000110111111011110110", 2 => "00111101100110011000011101000000", 3 => "10111011001100101101100100000110", 
    4 => "10111101111001100111000101101001", 5 => "10111100110100100001100110101000", 6 => "00111101011000001101111011010011", 7 => "00111101100010100010100011111110", 
    8 => "00111001110110101010000011001011", 9 => "00111101001110100011111011000000", 10 => "00111101110100110011000110100001", 11 => "10111101100100001100010011011111", 
    12 => "00111101110111011110110101101100", 13 => "10111011001001011001110000000110", 14 => "10111101011111111010110100101010", 15 => "10111011101110001011111011111001", 
    16 => "10111101011110100110000101011011", 17 => "00111100111000010101011001011100", 18 => "10111100001011011010111111010001", 19 => "10111101011100001101101001011110", 
    20 => "10111101010100110001000000010011", 21 => "00111011100011011010011111110100", 22 => "00111101100101000001010100101011", 23 => "00111100111001100010011101111100", 
    24 => "10111101000101110111011101001011", 25 => "10111101100101110001110000010001", 26 => "00111101001110111110010001000111", 27 => "10111010110110000010001101000010", 
    28 => "10111101110101010001011000010010", 29 => "00111101011011110100000001011111", 30 => "00111101001101111010011100000001", 31 => "10111101001111000010110110101110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

