-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_10_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_10_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111100010101001001110101111100", 1 => "00111100010000000010111100110000", 2 => "00111101101110001110000000000001", 3 => "00111101111010111010101001011000", 
    4 => "10111100111111010110100101001101", 5 => "10111101011100101110101111100110", 6 => "00111101101010011111111000000000", 7 => "00111101101101001001101011011101", 
    8 => "10111101110101001110011011100010", 9 => "00111101110010011110100100001000", 10 => "00111101101000100101000101111110", 11 => "00111100110010010000011000000011", 
    12 => "00111100111110010101001011010010", 13 => "00111101111000110111000001001000", 14 => "10111101001110000100000100100101", 15 => "10111011100000101000110000110111", 
    16 => "10111100101100010100010001000110", 17 => "00111101111110011000010100100111", 18 => "10111101100110001011110111101100", 19 => "00111101100011110001110111000101", 
    20 => "10111100101101011110111110100110", 21 => "00111101100011111010110011100110", 22 => "00111101010111000010011011011101", 23 => "10111101100001111110100111011001", 
    24 => "00111101111100110000011100101001", 25 => "10111101111011011001010110011010", 26 => "00111101011011011101110111110100", 27 => "00111100100011111010010110001111", 
    28 => "10111101111010010100000010111100", 29 => "10111100001010111011100010000000", 30 => "10111101000011100001110001011000", 31 => "00111101111011011110101010001001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

