-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_42_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_42_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101101010000101001111000001", 1 => "00111111000000001000010101011110", 2 => "00111111000000000000010010000110", 3 => "00111101110101001110111101000110", 
    4 => "00111101110011000100011010010101", 5 => "00111101010100111110000111001010", 6 => "00111110000100101101010101011010", 7 => "10111101001110001000001000101000", 
    8 => "00111110000011111110110000010100", 9 => "00111110000000111001110001010010", 10 => "00111101101001010000000011010110", 11 => "10111101100011011111000001001110", 
    12 => "00111101000100000110000101000001", 13 => "10111100011010010110100000001110", 14 => "00111101101100111010000001000000", 15 => "00111110000111110010100010000101", 
    16 => "10111101100001110000100001101000", 17 => "00111101000001011111101011101100", 18 => "10111101011100110001110000100010", 19 => "00111110000101000101111101011011", 
    20 => "10111101101011011100110010100111", 21 => "00111101011100100011001101011001", 22 => "00111101100000101101111000000001", 23 => "00111100100011110010010110100010", 
    24 => "00111101101111010111111101010010", 25 => "00111110000100111100010100110111", 26 => "00111100110110010011110001000111", 27 => "10111101010100000110101110111110", 
    28 => "00111110000100100000100000011000", 29 => "00111101000011111111011101011001", 30 => "00111011100111001010100111101111", 31 => "00111101010110011110101001010111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

