-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_29_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_29_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101001111101101101001100110", 1 => "00111101101110100001010001001001", 2 => "00111011110000111010100001100001", 3 => "10111101111001100001110100000000", 
    4 => "00111110011011100111110110011010", 5 => "10111101110111111010000000001110", 6 => "00111101011001001111100001110010", 7 => "10111101101101011011001011010101", 
    8 => "00111110011011100111110000000111", 9 => "10111101101100000010010101111101", 10 => "00111101100011000001101100010001", 11 => "10111100101001000110011110111110", 
    12 => "10111100100010000001111001000111", 13 => "00111100110111110001000101110011", 14 => "00111101110000100011100011011010", 15 => "00111110010011011000111010000110", 
    16 => "00111110111110000001010010110110", 17 => "10111101100110110111100011001101", 18 => "00111101000100111011100011100101", 19 => "00111110010101101001100000110101", 
    20 => "00111110001110010110010011101001", 21 => "00111101111111100010111011110101", 22 => "00111101101100100101100000001100", 23 => "00111100110011001010110101011000", 
    24 => "00111110100011010110000100001011", 25 => "00111110001001010101000110010011", 26 => "00111011100000000110101011110100", 27 => "10111101100011000100010001111100", 
    28 => "00111101111101110010111101110111", 29 => "00111110000010110000100010011010", 30 => "10111101111110000011011110110101", 31 => "10111100111001000000100001010011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

