-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_39_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_39_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101101011000111100001100100", 1 => "00111100110101111000101000101011", 2 => "10111101001111001110011000111010", 3 => "10111100111110110111011000101110", 
    4 => "00111011101110111001000001100100", 5 => "00111101100011010101011100110110", 6 => "00111011100001110010001010011111", 7 => "10111100011111011000011010101001", 
    8 => "10111101001101110011110100011001", 9 => "10111101100011110011001101000100", 10 => "00111100110111010011001101001100", 11 => "00111101001110000010011111111010", 
    12 => "00111100000011100101001111101011", 13 => "00111100110111111010101010001011", 14 => "10111100011011010011000011110000", 15 => "00111100110001001011110100110100", 
    16 => "00111101000001101001011100101001", 17 => "00111101011001110010110010010101", 18 => "00111101000110100010000111101010", 19 => "00111101010011110101000110101101", 
    20 => "10111100111000100101111010011010", 21 => "10111100110110111110111000111101", 22 => "10111100111010111000010100011111", 23 => "10111100101010001100000101010101", 
    24 => "10111011001111110011101111101011", 25 => "10111011001111000011100000101010", 26 => "00111100100110111011111100001110", 27 => "10111101100000100100000100111110", 
    28 => "10111100100000101001110011111110", 29 => "10111010101101110011110100011001", 30 => "00111101100011010101110011111011", 31 => "00111101010010111011000110101111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

