-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_3_63_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_3_63_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110110001011111000010110011", 1 => "10111100010010011111111110010011", 2 => "00111110001101111001110110010001", 3 => "00111101010001011101111110101000", 
    4 => "10111100001111011101001100110101", 5 => "10111101110000110011100100111011", 6 => "10111101100111000001000101011110", 7 => "10111110101011001001011001000110", 
    8 => "10111110011100001010100010001111", 9 => "00111101000111101010101110111101", 10 => "10111100101110010001110101011000", 11 => "10111101110001010010111011111001", 
    12 => "00111101001111010111010111100010", 13 => "10111110001111110101011011101011", 14 => "10111100110001111111000100110000", 15 => "10111101000110001100000010001011", 
    16 => "00111101110000110011110001100000", 17 => "10111100011001110100101011111101", 18 => "00111110101111100000111000110000", 19 => "00111110000001010000110001011111", 
    20 => "10111101000110010010110110011001", 21 => "10111100110000001100110001111001", 22 => "10111110000001010101001010100000", 23 => "10111101101101001010010101011001", 
    24 => "10111110001111011100001110111101", 25 => "00111110101100000001100101001100", 26 => "00111011111110011010100011001110", 27 => "00111110101010011111111011001010", 
    28 => "00111110000011101000111110110000", 29 => "10111101010000110001100010111001", 30 => "10111101110001101101011010011001", 31 => "00111110100110001000010110110010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

