-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_0_20_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_0_20_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101000010011010010101100101", 1 => "00111100100010010111100001001111", 2 => "10111101101111101010101010110000", 3 => "10111101010001011000000000111101", 
    4 => "00111101100011100010101100000110", 5 => "10111011100011100110000010000000", 6 => "10111100100011010110000010100110", 7 => "00111101110111110100110010110010", 
    8 => "10111101011101001000000110110010", 9 => "00111100110010000001011011110000", 10 => "00111101111100000101001100011010", 11 => "00111110000111111110011111100010", 
    12 => "00111110010001001110000011011011", 13 => "00111101011010000110111110001011", 14 => "00111101101001110100001010011010", 15 => "00111101111001001101010001000101", 
    16 => "10111101001110001011011110100010", 17 => "10111011111001101100000010010100", 18 => "10111101100010101101010101111100", 19 => "00111110001010011100111011010001", 
    20 => "10111101101100001111111010001011", 21 => "10111101000001011010110101010100", 22 => "00111101110011010000110000111101", 23 => "10111100100110110000100010011010", 
    24 => "00111101101001010100111011110100", 25 => "00111101011110010111101110110111", 26 => "10111101111111110001100001000100", 27 => "10111101010110000111110101110000", 
    28 => "00111101111010100011100010111001", 29 => "10111101010110101101001100100000", 30 => "00111100101011011111011100011111", 31 => "10111101011011011101100010110110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

