-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_51_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_51_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111100100010001010111011111011", 1 => "00111110001101111110111110011110", 2 => "00111101000100010111110001011111", 3 => "00111110010110101000001100101100", 
    4 => "00111100101100010001000111110001", 5 => "10111101010001101101100000101100", 6 => "00111101011111000110010000110100", 7 => "10111101101001111100100111011110", 
    8 => "00111101110000011011110000010010", 9 => "00111100000010010111101001101000", 10 => "00111101000111011010100010111101", 11 => "10111101100100011001110001011010", 
    12 => "00111110000011110001111111011110", 13 => "10111100001101111110110101000010", 14 => "00111101010010110110000111111110", 15 => "00111110000110101011111101110111", 
    16 => "10111101000110000001000101101111", 17 => "00111100101010010100010101110100", 18 => "00111101001100111000011000001010", 19 => "00111101110001100100101010011101", 
    20 => "10111100110110011010010100100010", 21 => "00111101010110101100111011101110", 22 => "00111101000010001010011110100100", 23 => "10111100000010000011111111010101", 
    24 => "00111010100100101110111010000101", 25 => "00111101100100010001000111110001", 26 => "10111101100101101000110001101001", 27 => "00111101101100110010110111110101", 
    28 => "00111110001011011011101000001010", 29 => "10111101010011011100101010001110", 30 => "10111100111010100110010111001111", 31 => "10111100001011001110101010101111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

