-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_72_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_72_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111100101111001101001101011011", 1 => "10111101101010100011001011110100", 2 => "10111100110110101101001100100000", 3 => "00111101001000101110010111011110", 
    4 => "00111100011010000010110101111011", 5 => "10111101011101110101101110000001", 6 => "10111101010010001101010111000111", 7 => "00111101011011100101000101001100", 
    8 => "10111111100011111111001101001001", 9 => "10111101010011000000101011010000", 10 => "10111101011011001110110111010101", 11 => "10111100111001111010100101011101", 
    12 => "00111101010100010011101101011100", 13 => "00111101011001010101000010000111", 14 => "10111101100000001110110011111010", 15 => "10111101100010111110001101111110", 
    16 => "00111111001101110010011000011000", 17 => "10111101111000101111000111101101", 18 => "00111101000000000010010010110011", 19 => "00111101010110000110110110110101", 
    20 => "10111110001010100110111001110110", 21 => "00111100100101010110010111000011", 22 => "00111101101111010101001111001110", 23 => "00111001101100011011101111001111", 
    24 => "10111101111100100110010000011011", 25 => "00111101000100000010110111100000", 26 => "00111110000001000101000110111001", 27 => "00111101001010011101011100110100", 
    28 => "10111101010100100101101010101011", 29 => "00111101100001000001111111101011", 30 => "10111101010011011010101100011001", 31 => "00111110000111110001100100001101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

