-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_3_46_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_3_46_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101100110110110100110011000", 1 => "10111100011100111110000000110111", 2 => "10111101111001011100101110111100", 3 => "00111101010111101000010111111101", 
    4 => "00111100111010000100101011011000", 5 => "00111101101111111001100111000100", 6 => "10111101111111010110010100011011", 7 => "00111101010000001101111101011001", 
    8 => "10111101101011001010000011000011", 9 => "10111101100100010001111110010010", 10 => "10111101010010000011111011001001", 11 => "10111101111101100011111111011101", 
    12 => "10111101110110000010011111111010", 13 => "10111101100000000010000110001110", 14 => "10111100110001110110101011111001", 15 => "00111100011101000010111111101000", 
    16 => "00111101111001010000101111011000", 17 => "00111101101110100111010011000001", 18 => "00111101100111001111111101100101", 19 => "00111100000001110101100100100101", 
    20 => "00111101100000111100011111010110", 21 => "10111100101101111010111001011000", 22 => "10111101001001010010011110100010", 23 => "00111101100000100110111001010100", 
    24 => "10111100101110100001001010110110", 25 => "00111100001111001110010000100001", 26 => "10111011010110110110101000011111", 27 => "00111100101000110100011001010110", 
    28 => "00111101110011010010000110111100", 29 => "10111101001011011111101101010000", 30 => "10111011000000101001110011111110", 31 => "00111101101110000000000100101110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

