-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_2_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_2_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101000001000111101000011000", 1 => "00111101100110111111010010001000", 2 => "10111100100101010101101101000110", 3 => "00111101011011101111001111010100", 
    4 => "10111010111001111011110000111100", 5 => "00111101100000100010101010110010", 6 => "00111100110001110000010000110110", 7 => "10111100100000100111010100100101", 
    8 => "00111101100111001100110000000011", 9 => "10111101111000100001111000011101", 10 => "10111101111111011001010101010111", 11 => "10111100110011011111000001001110", 
    12 => "00111101011011001111000011111010", 13 => "10111110000000001110100010000110", 14 => "10111100101101011101111011011111", 15 => "10111101111101000110000000100100", 
    16 => "00111101110010000111000110100100", 17 => "10111100111111101011010010100110", 18 => "10111101110000100101010100101010", 19 => "10111101001100101010011110111101", 
    20 => "10111100100100011110010000101110", 21 => "00111100000110110000011010000001", 22 => "10111101100001111010011101000100", 23 => "10111100101110110100110101001001", 
    24 => "00111101101110111000011101111011", 25 => "10111101100100000111011011000000", 26 => "10111101101010111110011010100011", 27 => "00111101111000111110100001010111", 
    28 => "10111110000001111010010010100101", 29 => "10111101111010001101100101110011", 30 => "10111101111100011111101000110011", 31 => "10111011101011010100111101011001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

