-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_96_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_96_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101010000100100100000001111", 1 => "00111011110111001010100011100011", 2 => "00111101000011000111010010111000", 3 => "10111100001001111011000010110100", 
    4 => "00111101000100011101010001110100", 5 => "00111101010110001100000010001011", 6 => "00111101011110000000101110101010", 7 => "00111010101100000010100100101000", 
    8 => "10111101011001000011100010001111", 9 => "00111101011000101100000000011110", 10 => "10111101100011110100001001111000", 11 => "00111101000100101100100011000101", 
    12 => "00111101100100110100001111111010", 13 => "00111100101100010001010000001010", 14 => "00111101010111011000011000100011", 15 => "00111100101110010100110110010100", 
    16 => "10111011100111010001011011111101", 17 => "00111101100010010010011110010001", 18 => "10111101001111000000110100101100", 19 => "10111101011111001010000100000110", 
    20 => "00111101010110010110111110101000", 21 => "10111101100010100101011100100001", 22 => "00111101010110000110011101101010", 23 => "10111101000100100011111001011100", 
    24 => "00111101100010011110000010100100", 25 => "00111101100011111111011101011001", 26 => "00111101001100111001111100110100", 27 => "10111101101000000000001000011001", 
    28 => "10111100000011101001001011010101", 29 => "10111100110010010100101100111000", 30 => "10111100110100111110111101101011", 31 => "10111101001011100100101100000010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

