-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_3_19_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_3_19_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110010100111011111001100110", 1 => "00111100101111011111001010101010", 2 => "00111101111111111110010111001001", 3 => "10111101011110111111100000110100", 
    4 => "00111101100001100011101011100010", 5 => "10111101000111010000011101000010", 6 => "00111110010011100110101111000110", 7 => "10111101101100000000010001110101", 
    8 => "00111101110010000011001101000000", 9 => "00111101100011100111100010011110", 10 => "00111101111000101111100010111110", 11 => "10111101110110011011010111101001", 
    12 => "00111110011100010011101001010000", 13 => "00111100110000010100100000110100", 14 => "00111110001010100010010110010110", 15 => "10111100110001110110001010010101", 
    16 => "00111101010001001010101101100000", 17 => "10111101001010111001011011110010", 18 => "00111110000010000011100111001110", 19 => "10111101000011000100101111010011", 
    20 => "00111101101001111001111001011010", 21 => "00111100000100111000110111100111", 22 => "10111101111010100111111001110100", 23 => "00111100100101110101011011001001", 
    24 => "00111101010010101101111011101100", 25 => "00111101111011101100010100101010", 26 => "00111101001111001100010010101100", 27 => "00111110010110100110010010000000", 
    28 => "10111101100000110110110110101000", 29 => "10111101101000011011001100101001", 30 => "00111101110011010011011100111011", 31 => "00111110011001010010111011111001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

