-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_55_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_55_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110110001011100010101010000", 1 => "00111101101001110111111011100101", 2 => "10111111001100100010010101010011", 3 => "00111110000011110001011110111110", 
    4 => "10111101010001001110010100001100", 5 => "10111101001110110101010110101100", 6 => "11000000011000000001111011100110", 7 => "10111100010011101101110101001000", 
    8 => "00111100110011000000001101111001", 9 => "10111101011110000000000000100010", 10 => "00111110110111111000110111111000", 11 => "00111101101010111111001010110010", 
    12 => "10111101101101000111010100011101", 13 => "00111101001010100111011010010110", 14 => "00111110011010011101000010100110", 15 => "00111101100001001001110000101100", 
    16 => "10111110010001110110110101010101", 17 => "00111010010111011100011000011001", 18 => "10111101100011000100110111101100", 19 => "00111101011011011111111110000010", 
    20 => "00111101000010110110100101010101", 21 => "00111110100111111101111101011101", 22 => "10111101100111010001000000101100", 23 => "00111101101101110011010100111011", 
    24 => "10111110000001011011001000001100", 25 => "10111110000101000100011110000000", 26 => "10111100111110110100001111011001", 27 => "10111110000000110101101100001100", 
    28 => "00111110000010111100100110001010", 29 => "10111111000000101001101101101011", 30 => "00111101010001110110011011000111", 31 => "10111101011000000011001011011011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

