-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_119_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_119_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101100000001101001011000100", 1 => "10111101010110001011111101111111", 2 => "10111101010000001111100110010000", 3 => "10111101000010100110010101001001", 
    4 => "10111100011001111001001001001011", 5 => "10111101001110101000011000001110", 6 => "10111100111010100101101101010011", 7 => "10111101101001101110100111111111", 
    8 => "00111100000011001011100011100001", 9 => "00111101100010111000010100011111", 10 => "00111101010001111011011001111000", 11 => "10111101101010100100000000010000", 
    12 => "00111100101001110001011110011100", 13 => "10111101100000001000010110110010", 14 => "00111101100010000111010011001001", 15 => "10111100000010001101101100000101", 
    16 => "10111100100110110011101011101111", 17 => "10111101100101011111001111011000", 18 => "10111101101001101100010000111111", 19 => "10111010100111111000001110111110", 
    20 => "00111011101111100000110111101101", 21 => "10111101100001001011011101101111", 22 => "00111100110111110011100101001011", 23 => "10111101101100001111000011101001", 
    24 => "00111011111101111111010010011001", 25 => "00111101011111000101011010010011", 26 => "00111101011101110111000110000110", 27 => "10111101011001100110010001001110", 
    28 => "00111100110111111110011101011100", 29 => "10111101100100101000001110010000", 30 => "10111100100011101100010100101010", 31 => "10111101011011101000100111101100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

