-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_91_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_91_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101000010111010100000111111", 1 => "00111100001111011011000110100111", 2 => "10111100101011101001001001001111", 3 => "10111011011001000100001100001011", 
    4 => "10111011111100011010000110011000", 5 => "00111101011111000010100001110000", 6 => "10111101101011010000011110000101", 7 => "10111101100100011011000001000111", 
    8 => "00111000110100111100111111110110", 9 => "00111101100100101100000001100010", 10 => "10111100111000001111011111111101", 11 => "00111101011001011001000001111110", 
    12 => "00111101100101011100101101111001", 13 => "00111101101000101111001011111010", 14 => "10111101001011100010110010011001", 15 => "00111100100111100100000011001000", 
    16 => "00111101010010011010011001110010", 17 => "10111100000101111000000010111011", 18 => "10111101100101010011101011000101", 19 => "00111101100100000000111111111110", 
    20 => "00111101001010101000101010000011", 21 => "00111100101010111111000100100000", 22 => "00111100100111010101010111100111", 23 => "00111100101000010000010110011111", 
    24 => "10111101010000100100011100000010", 25 => "10111011111111111111001101101011", 26 => "00111101010101000111011010110000", 27 => "00111101011001010011011001010000", 
    28 => "00111101010100100110101101110010", 29 => "00111101010100110100001001101000", 30 => "00111101100010100100101100010010", 31 => "00111101110001111000011111001111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

