-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_57_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_57_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110001011101000010000100111", 1 => "00111101111000001111110100111011", 2 => "10111111101010110011111011001101", 3 => "00111101100110110010111101100110", 
    4 => "00111110010010100110101100001110", 5 => "00111101101110110011100011010110", 6 => "10111110011101000111011101111001", 7 => "10111101111001101011101001001001", 
    8 => "10111101111100000010111111111001", 9 => "10111110000001010010110111101101", 10 => "10111101101100110111101110001101", 11 => "10111101011110011111001000110100", 
    12 => "00111011000110010110101101110110", 13 => "10111101101011001101101001101110", 14 => "10111101101111101001010000100101", 15 => "00111100101110011100111110011010", 
    16 => "00111110001111111101011111100100", 17 => "10111101100001111101110101000100", 18 => "00111101010010011111100101001000", 19 => "00111100001111001100001010010100", 
    20 => "00111011101000001010100101011000", 21 => "00111100111100000001100101101110", 22 => "10111101011001110111101100111001", 23 => "10111100110111001110101111111111", 
    24 => "10111101110011010010001111010101", 25 => "00111100111000100110010011100101", 26 => "10111101000010010111001000000100", 27 => "10111101010000010100100000110100", 
    28 => "10111101010101000100000000101001", 29 => "10111101001001101100110000011101", 30 => "10111101110010101100110100011000", 31 => "00111101000111011100111001111101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

