-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_60_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_60_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101001010010000000101001011", 1 => "00111110100001011000010011010011", 2 => "00111110100111100001000101110111", 3 => "10111101111010001111011111011011", 
    4 => "10111110011100101101010101011010", 5 => "10111101001111110010101100100100", 6 => "00111100100010110110101101101110", 7 => "00111101011001110011100100101010", 
    8 => "10111110100000101000101101001100", 9 => "10111100111001001011000000011000", 10 => "00111110010001011010011010000011", 11 => "10111101010110100010100000110101", 
    12 => "00111101100001110100110110011100", 13 => "00111101101011110100001110000101", 14 => "00111110011010100000010110011010", 15 => "10111111000000110110010000111001", 
    16 => "10111110010001001111001011110001", 17 => "10111011001001100101010010010011", 18 => "10111110000000101110000110101100", 19 => "10111101100110101110111001100011", 
    20 => "00111110011110010111001101010100", 21 => "10111101100000101000000110111010", 22 => "00111101101100110100001101110100", 23 => "10111101011101111000100010011000", 
    24 => "10111100110001001100110111111011", 25 => "00111110011010011001101100101100", 26 => "10111101110010000101001000101111", 27 => "10111110101000000010011111111010", 
    28 => "00111110000000001011101001100010", 29 => "00111101001001010100001111110010", 30 => "00111110001000001100110010111100", 31 => "10111110101011011000011001100110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

