-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_10_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_10_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101101100101001011011110110", 1 => "10111101110101100000100011010001", 2 => "00111100100010011111110001101110", 3 => "10111101111101100100111100010010", 
    4 => "00111100011000110010000110100011", 5 => "10111101011001001011001100111110", 6 => "00111101001001011010000101000101", 7 => "10111101111111101000101010110101", 
    8 => "00111101001000101001100001000110", 9 => "10111101000010000111001100110110", 10 => "00111101111000101101011110110110", 11 => "00111101110110011100101101101000", 
    12 => "00111101110100010101111100000011", 13 => "00111101100111001101010011101101", 14 => "00111100110111110010111011001111", 15 => "00111101101010100111000011010010", 
    16 => "00111101100000000100111010100101", 17 => "10111101011010111011001000110101", 18 => "10111101111101010110111010101101", 19 => "10111101101010110011010101101110", 
    20 => "10111101111000101001111000001010", 21 => "00111101101010001100101011000101", 22 => "10111100011000001100100111011010", 23 => "00111100110010010010101111000011", 
    24 => "00111101100010100011101011010010", 25 => "10111101111111110110001010110111", 26 => "10111100110011011011100111000111", 27 => "00111101110110011100101011100010", 
    28 => "10111101101111101001000100000000", 29 => "10111101111000000011101010111000", 30 => "10111101001110101110010101111001", 31 => "10111101001110001011100010101110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

