-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_3_58_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_3_58_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111111001110010011101000011101", 1 => "00111011110101111110100010001010", 2 => "00111101100000001011101110110010", 3 => "10111101011001100110101110100101", 
    4 => "00111100100101010011010110000111", 5 => "00111100111111111111000101010010", 6 => "10111100110010100000001111000101", 7 => "10111110011001011101101110111010", 
    8 => "10111111001010000000000010111001", 9 => "00111101101100010110101110011000", 10 => "10111110000000110101111001110100", 11 => "00111101110101001110001000101010", 
    12 => "00111101011000011010111101111101", 13 => "10111110110111000010101111111010", 14 => "00111100110000010010100010111111", 15 => "00111101100010101010010010111010", 
    16 => "10111110101110011001011010110111", 17 => "10111101001101100111110100110101", 18 => "00111110101011001010111100001100", 19 => "00111110111100101111010101010110", 
    20 => "00111101101000101100010001010000", 21 => "00111100110101010111011110010110", 22 => "00111101101011001110101110111100", 23 => "00111100110000100101000001110010", 
    24 => "00111101011000101000101110110001", 25 => "10111101101010100101010100001000", 26 => "10111101111110011110011010101100", 27 => "00111111001011101001011101011011", 
    28 => "00111111010001111100100110111100", 29 => "10111101100110110100011110000100", 30 => "10111101101101111111111100010101", 31 => "00111110100101010001011010111001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

