-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_112_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_112_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101001110100011100110000010", 1 => "10111101111000011000111001110101", 2 => "00111101001000110101001011101011", 3 => "00111010010010110010100101011111", 
    4 => "00111101000101100011000100101111", 5 => "10111101001000111001001011100010", 6 => "10111101111011100010011111100001", 7 => "10111101101001111111011001101111", 
    8 => "00111100100010100101000001010000", 9 => "10111100110001000010111010011001", 10 => "10111101011101111101000011110010", 11 => "10111101010111100001100111111100", 
    12 => "00111101101010101111111101101101", 13 => "10111011000010111010100000111111", 14 => "00111101000010011000110101000111", 15 => "10111101101011011011110101110011", 
    16 => "10111110000000111000111101111010", 17 => "00111100000100101100110011110111", 18 => "00111011000010110100001110010110", 19 => "00111101000100011000000110011101", 
    20 => "00111101000010100000000010011111", 21 => "00111101001101101111010111001011", 22 => "00111101100010011100001111001110", 23 => "10111011010000110001100111000110", 
    24 => "00111100000000110101000101011001", 25 => "10111100010101101001110100110000", 26 => "00111100101111111110111000101101", 27 => "10111100100010011001101111110110", 
    28 => "00111101101111000010011111101001", 29 => "00111101010000001111000100101100", 30 => "10111101001100010100001000101101", 31 => "00111101100111110011101111101011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

