-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_78_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_78_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110010110001101101111001111", 1 => "10111101100101000101100001000111", 2 => "10111101101110101100011000000100", 3 => "10111000101001011010110011001101", 
    4 => "00111110001000100110010000011011", 5 => "00111101111101010100110110100101", 6 => "00111101010001111110000101110110", 7 => "10111011110101111011011000110101", 
    8 => "00111101101010000011100110001010", 9 => "10111101001000101011011110111011", 10 => "10111100110100101001111111100000", 11 => "00111101011001110010111110111010", 
    12 => "10111101010001001110101001001011", 13 => "10111101001011000011111111000100", 14 => "00111101011010000100101011011000", 15 => "10111101100011110001111011010001", 
    16 => "10111100110110110010000010111000", 17 => "10111101101000101110111111010100", 18 => "00111100101011100000001110110100", 19 => "00111100010101000111101111101110", 
    20 => "00111011111011001110100110100011", 21 => "00111011010110001000011111101100", 22 => "10111101000000100011101001101101", 23 => "10111011001000011010110101100100", 
    24 => "10111101101000001101001101001010", 25 => "00111101100000001100000001101010", 26 => "00111101100100010111110101101011", 27 => "00111110001001001111100001110010", 
    28 => "00111110001001011000100010100000", 29 => "00111101011100010010010111011101", 30 => "00111101101111011111111100111111", 31 => "00111101101111101111001100001010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

