-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_65_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_65_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110111001001100010010001011", 1 => "10111100011010011000010101101010", 2 => "00111100101010101000111010110100", 3 => "00111101100000001111000000100000", 
    4 => "00111110000011101000011110010000", 5 => "00111110101011100101010011111000", 6 => "00111101001101111000111011100011", 7 => "10111100110101111111100101010001", 
    8 => "00111110000011011101111110000111", 9 => "00111101101011100111110101010110", 10 => "00111101111110000100010101010110", 11 => "00111101010001110001010011111101", 
    12 => "00111100100110100011010011001010", 13 => "00111011001010110111000100110010", 14 => "00111101000000111110111010100010", 15 => "00111011001001001010000001011110", 
    16 => "00111100101110010111110111010000", 17 => "10111101100001110110001100011011", 18 => "10111101101110000100001111000100", 19 => "10111100100100100110110001111111", 
    20 => "00111101101010010110000111000011", 21 => "10111100010110000110101010010000", 22 => "00111100111001011000011000000001", 23 => "00111101000000110011000011010111", 
    24 => "10111101100111001010001010011000", 25 => "00111101100000100010010011101110", 26 => "00111100101001111000111100100110", 27 => "00111110000000001100101110110000", 
    28 => "00111110111001010111010000001100", 29 => "00111101101111110010001000111010", 30 => "00111100111001011001010010101111", 31 => "00111101000100100110110110001011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

