-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_111_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_111_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111111101000110011111101000010", 1 => "00111111100111000111110000011000", 2 => "00111111010111100011011111011111", 3 => "00111110000111101010111100100101", 
    4 => "00111101100101001110101100010100", 5 => "10111001111000011111011111010111", 6 => "00111111000100010110101001111011", 7 => "00111110111011001101011100000110", 
    8 => "00111110111010110011111001010111", 9 => "00111111010110011111010000101100", 10 => "00111011011001010001110100100110", 11 => "10111101111001000011101110110100", 
    12 => "00111111001000101011110100011011", 13 => "10111101110001101001010100010000", 14 => "10111111001101011100010001000100", 15 => "00111110000101100110011100110000", 
    16 => "00111110101001100010000101110101", 17 => "10111111101110110001110111010110", 18 => "10111100101100100101001011001110", 19 => "00111101000101100101111001000110", 
    20 => "10111111100001100010010000110101", 21 => "10111100011111011110101101010011", 22 => "10111101001001001010101011011010", 23 => "00111110100010011111100101101010", 
    24 => "10111110101100110010011000111001", 25 => "00111110101100010011010010001011", 26 => "00111110100010101111010110011001", 27 => "10111101011110110001000001110111", 
    28 => "00111111100100110111010001011000", 29 => "10111101100000101000000110111010", 30 => "00111110110010111110111100000111", 31 => "10111101100111011011010101010010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

