-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_62_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_62_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101100110101101001010011010", 1 => "00111101010101100101110000101101", 2 => "10111101110000110111100110110111", 3 => "10111101101111010100011000101100", 
    4 => "10111100111111110010111001001001", 5 => "10111101101011001100111011100110", 6 => "00111101010001000001100010010011", 7 => "00111101111000100100000100111110", 
    8 => "00111011100111011011111011000010", 9 => "00111101110111110001100111010110", 10 => "00111101011010111101101100011010", 11 => "00111101001100110011000100011010", 
    12 => "10111101011101110011000110010000", 13 => "10111100101110000000111011010000", 14 => "10111101011101100011010111100111", 15 => "00111101011100111010111011101111", 
    16 => "00111100111000010011111101001011", 17 => "10111101001010111010110011110111", 18 => "10111101101010011011110110000100", 19 => "00111010010100011011011100010111", 
    20 => "00111100101011001101010110110111", 21 => "10111110010000101111101011010111", 22 => "10111110000000001000011110000111", 23 => "10111110000001100010001111010001", 
    24 => "10111011101010101100000100001001", 25 => "00111101101010111110110111111010", 26 => "10111101100011111001110010100110", 27 => "10111011100011000100011110100001", 
    28 => "10111101101101100100000101110000", 29 => "10111101101100110100010100000111", 30 => "10111110000101001111001000101000", 31 => "00111101100110101000001011101000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

