-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l1_p_ZL2W1_0_0_RAM_1P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l1_p_ZL2W1_0_0_RAM_1P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111110001111000000111001111100", 1 => "00111110010100010010010001001010", 2 => "00111101100011001010101100111111", 3 => "00111110010011111010000011010111", 
    4 => "10111110100110001101110000110011", 5 => "10111110000111000101011100011001", 6 => "00111110011010010110011010111110", 7 => "10111110100011011010110110010111", 
    8 => "10111110001011110100000101101100", 9 => "10111110110110101111001011111010", 10 => "00111110000101100111110001101100", 11 => "10111110101100001101110001110111", 
    12 => "00111110011010111001010010010110", 13 => "10111110111001001000110010110101", 14 => "10111110101000111010110000101110", 15 => "00111110000101101011100111000011", 
    16 => "00111110100101100111010101111001", 17 => "10111101111110100010000011011110", 18 => "10111100100001000101011101111110", 19 => "00111101011001001100101001001111", 
    20 => "00111101111001111000001000001010", 21 => "00111101011111100100011110011001", 22 => "10111110010110011110111000000011", 23 => "00111100100111010001100100010101", 
    24 => "00111100010010010101011111001101", 25 => "00111101100000001111011101110111", 26 => "00111101100011010001011101000000", 27 => "00111110011011100000111001110011", 
    28 => "00111110000100010001011110110101", 29 => "10111110010110011011110010111010", 30 => "10111110110011000101000010101101", 31 => "00111101001101111001100101011111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

