-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_125_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_125_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101101001001000010010010100", 1 => "00111011101010000011001010111010", 2 => "10111101110010010010101111000011", 3 => "00111100110100101111111000111111", 
    4 => "00111100111011111101100001101011", 5 => "10111101010001111101100100010010", 6 => "10111101010011010000110111010000", 7 => "10111101000110010011101000101110", 
    8 => "00111101100010101000111010110100", 9 => "10111101100101011000011101010001", 10 => "00111101001100000111100011011001", 11 => "00111101001111011110001111111100", 
    12 => "10111101001110101110010001101101", 13 => "10111101100111111010100101111110", 14 => "10111101011101010001001001100110", 15 => "00111101100111100110111101110010", 
    16 => "00111100100100100111001011001001", 17 => "00111100001000111101011100001010", 18 => "10111101101100100010001110011110", 19 => "10111101001001101111001111110101", 
    20 => "10111100011011011101110011101000", 21 => "10111101000101100000111110100001", 22 => "00111101001001010001010011000010", 23 => "10111011101101001111101001001000", 
    24 => "00111101001110001011010001111100", 25 => "10111101011100110011111010111100", 26 => "00111101101000110010110010100101", 27 => "10111101100010111001100010000101", 
    28 => "10111100100001110100101001110111", 29 => "10111101010100110000100111001000", 30 => "00111101100010110000111000011011", 31 => "10111101011010111111100110000011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

