-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_13_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_13_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101101010101111000010111111", 1 => "10111101110101101110011010010111", 2 => "00111101111111101011101111111101", 3 => "00111100100110110010001111011101", 
    4 => "00111100111010111011001101000010", 5 => "00111100111011001010110011010010", 6 => "10111100111000001001101110110111", 7 => "00111101111010110010010100101101", 
    8 => "10111101111100010111010010000010", 9 => "00110110000001100011011110111101", 10 => "10111101100001010100111011110100", 11 => "00111101111101100100000001100100", 
    12 => "10111101101111110000111001001110", 13 => "10111100100110110111010110100111", 14 => "00111101100111101010011110001011", 15 => "00111101101101000000010011101010", 
    16 => "10111101000100110100110011100100", 17 => "10111101011011110111010011001101", 18 => "10111101001100101100010100011001", 19 => "00111101101011100101011110010111", 
    20 => "00111101100100110010011110101010", 21 => "00111100111101010111101101000010", 22 => "00111101011000110110110100100010", 23 => "10111101111111001000111110111000", 
    24 => "10111101101111101011110100001010", 25 => "10111110001001011010000111001011", 26 => "00111010110101110011100001100001", 27 => "10111101100110110011001110011000", 
    28 => "00111100011010011110101000010100", 29 => "00111100110100110011101100010000", 30 => "10111100110001000111111001001010", 31 => "00111100110011001010110101011000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

