-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_34_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_34_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101110100011101000011001000", 1 => "00111101111100111101100011100000", 2 => "00111101100110100000011010100111", 3 => "00111100111011010111100000111110", 
    4 => "10111011011001001100100101000011", 5 => "10111100010011000111010010111000", 6 => "00111011010111100001100111111100", 7 => "00111100000001101001100000110101", 
    8 => "10111011100000110000000110101000", 9 => "00111101001001111001000000110010", 10 => "10111100101101110011000010000011", 11 => "00111100110000110011001011110000", 
    12 => "00111100111100101100111110010110", 13 => "00111101110000010011101100011001", 14 => "00111101110101010111101111001000", 15 => "10111101001111110110011111110101", 
    16 => "00111101011101101001000000010101", 17 => "00111101100001011010110001000111", 18 => "10111011110110011000001110010100", 19 => "00111101100100010101010110010011", 
    20 => "10111101111000010100101111100000", 21 => "10111101100100100011111011100010", 22 => "00111101011100000100100010011101", 23 => "00111101110000110010000000010000", 
    24 => "10111100110001100101100000111111", 25 => "10111101011100110101010111001110", 26 => "00111101111010110000110000000010", 27 => "10111101001010110101100100010100", 
    28 => "10111101101011101111011101111111", 29 => "00111101110011000010101011001100", 30 => "10111100111011001100010111111100", 31 => "10111101011010000000010110100011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

