-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_1_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_1_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101100010011001110110001000", 1 => "00111100110001111001010011101010", 2 => "00111101011100010101000111100111", 3 => "00111011011011111110110101100011", 
    4 => "10111101001010100000010001001011", 5 => "00111101001111001010100001011101", 6 => "10111101101010010011111010100011", 7 => "00111100110111000101000011001110", 
    8 => "10111101011101100001101110110000", 9 => "10111101000100001101010110100110", 10 => "10111101000000000000110010010101", 11 => "00111101011000100111001110010011", 
    12 => "10111100100001101111010001111011", 13 => "10111000100100001011010000011000", 14 => "10111101011001111010001100010010", 15 => "10111101100000111000111110111101", 
    16 => "00111100001011011010111111010001", 17 => "10111101011110101110100010011111", 18 => "10111110000011000110100111111001", 19 => "10111101101101101001001111000000", 
    20 => "10111101001100000100111111110100", 21 => "10111101101100011000010101001001", 22 => "10111101001011000111000100001101", 23 => "00111101100111101111111110100000", 
    24 => "10111101010000001100000011110000", 25 => "00111011010010100001110011101111", 26 => "00111101100111110110100100000001", 27 => "10111101100001011010011110001111", 
    28 => "00111101010101111111010100011111", 29 => "10111101011000100110101100101111", 30 => "10111101011010000100111100001001", 31 => "10111101010111010011010001011001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

