-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_0_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_0_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111100011000110110000010001101", 1 => "00111110010010011010010010011100", 2 => "00111110001001110000010011111111", 3 => "00111110010101000100111101011101", 
    4 => "10111101010001001001110010110010", 5 => "00111101001011100100011111011100", 6 => "00111101100110000111110011101001", 7 => "00111100010111111011010100000111", 
    8 => "00111100110010011100010011011011", 9 => "00111101101010101000111000101110", 10 => "10111101101010101010000010001000", 11 => "00111101001011011100011011100011", 
    12 => "00111110001101011010111001100000", 13 => "00111011100010110100001110010110", 14 => "00111100011001110000110000010011", 15 => "00111101110011001010000101001001", 
    16 => "00111101000100101010001100000101", 17 => "10111101101001011011111010100001", 18 => "00111101100010101101111101110010", 19 => "10111101000101001101101001001101", 
    20 => "00111101100101101101100011110101", 21 => "10111100001111100011001110101101", 22 => "10111101101100001011100101010110", 23 => "10111100101111000010011101100011", 
    24 => "00111011101011111001101010001101", 25 => "00111101011010011011011110111111", 26 => "00111100110010111010101101100101", 27 => "00111101010100100101110111010001", 
    28 => "00111110010011111011101000000010", 29 => "00111101101001010111011001000111", 30 => "10111100101101110101111010100110", 31 => "00111101100011111001100110000000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

