-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_95_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_95_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101100000111011001011011101", 1 => "00111100101010001111110000001101", 2 => "10111100110110000010101110100110", 3 => "00111100001010110100101101110011", 
    4 => "00111101000111001011001001010011", 5 => "00111101001011001001010111000000", 6 => "00111100001111011011101000001010", 7 => "00111101100000001010000001101111", 
    8 => "00111101001100001011001010000101", 9 => "00111100110111110011011100110011", 10 => "00111101100001010110101010111110", 11 => "00111101000011101110010110101100", 
    12 => "10111101110111001011000011000000", 13 => "00111101011101100011111001001011", 14 => "10111100001011111110111001110000", 15 => "00111100111001111101100110011001", 
    16 => "00111011101000010011011111110100", 17 => "00111101001010001001001100110010", 18 => "10111101001110010011001001010001", 19 => "00111101000010110011000111000010", 
    20 => "00111101101100111011001010011010", 21 => "00111101100111111101111101111111", 22 => "00111101101110000101100010111100", 23 => "10111101010010000110010010001000", 
    24 => "00111101111000101010100010000111", 25 => "10111101011101010000000010010011", 26 => "10111100110011111111101001111111", 27 => "10111101000000111101001001010010", 
    28 => "00111100110101110000011000001100", 29 => "00111101100001110000101110001101", 30 => "00111100101010110011101010101100", 31 => "10111101011001110110010100110100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

