-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_27_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_27_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111100000000010011010001001000", 1 => "10111110000001110100110001001101", 2 => "10111101100111010011100000000100", 3 => "10111101100101011000000110001100", 
    4 => "00111110001000111110010111111011", 5 => "10111101100010001011010011000000", 6 => "00111110001101100111100011000000", 7 => "10111101100011010110000110110011", 
    8 => "00111110011101110100001011011101", 9 => "00111101000001111101101100101011", 10 => "00111010010001101111011110100001", 11 => "00111101000101011000111110110100", 
    12 => "00111101010110001001001101110101", 13 => "00111101100001010011010010111101", 14 => "00111101111000011101010010110111", 15 => "00111101000110110111011111000000", 
    16 => "00111110001110011000001110010100", 17 => "00111101000100101111001111000011", 18 => "00111101011001111111000110110111", 19 => "00111110000000110110111011111000", 
    20 => "10111011011010110000001100011001", 21 => "00111110010010000010000111110011", 22 => "00111101101010101011101010111111", 23 => "10111101011101110010111101110111", 
    24 => "00111110011100011011110111101000", 25 => "00111110000110100100010010000101", 26 => "10111101100000101110010001001011", 27 => "00111101110100000100110001001001", 
    28 => "00111110000001100000001010000110", 29 => "00111101000110100100110011101000", 30 => "10111101110101111011101101110011", 31 => "10111100111001001010010110011100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

