-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_19_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_19_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101000011110111011001100000", 1 => "00111011101111011010100101000011", 2 => "00111101100101101110101011001000", 3 => "10111101100001110010101001111100", 
    4 => "10111101101010001110101000111010", 5 => "00111101100100111111010010101010", 6 => "00111101010111011000110101111010", 7 => "10111101010011101010001110011100", 
    8 => "00111101010100111010001011100000", 9 => "10111101010001011110110000111110", 10 => "00111101100000010100010010001001", 11 => "10111101011100111001011111011101", 
    12 => "10111101001001111111000010101010", 13 => "10111100111001011111101101110010", 14 => "10111101100101110100001101100011", 15 => "10111001111001100010100110010101", 
    16 => "10111101001011111011010011000100", 17 => "00111101101001101000011111110100", 18 => "10111101010001001110100000110010", 19 => "10111100100110101000100010101101", 
    20 => "00111101011010110100110110001100", 21 => "10111101101011000000110111110110", 22 => "10111100010110110010111101100110", 23 => "10111101101000000111101100110101", 
    24 => "10111011101110001000010001000000", 25 => "10111101001011100101011110010111", 26 => "10111101010101010111011010001010", 27 => "10111101011101010001000001001101", 
    28 => "00111100110000010100111001111111", 29 => "10111101011101101110101101001111", 30 => "10111101100001111101100110011001", 31 => "00111100101010101001110101100010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

