-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_88_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_88_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101110011001000100010100100", 1 => "00111101111011100000111100111101", 2 => "00111110001000000111110010000101", 3 => "00111110000010010001100011100011", 
    4 => "00111101110011100101000011000110", 5 => "10111101100100011101100100101011", 6 => "00111110001011011101010110010001", 7 => "00111101101011001011010110111011", 
    8 => "00111110010011101011001101010111", 9 => "00111110011000001011011001110100", 10 => "10111101101000111100000001111111", 11 => "10111101111001111000011011000010", 
    12 => "00111110010010100001011110110001", 13 => "10111101010111000011011010010111", 14 => "10111110010001001111000010010101", 15 => "00111110100010111011000000011101", 
    16 => "10111110000100100111001000000000", 17 => "00111011100010110010001000001000", 18 => "00111100100110000010010001001111", 19 => "00111101110110000001011100110011", 
    20 => "10111110100010101110010111011110", 21 => "00111010000011100001010100000001", 22 => "10111110000010100101001001101001", 23 => "00111101011010111011001000110101", 
    24 => "10111110001000110111100110110111", 25 => "00111110001100011000001001100110", 26 => "10111110000111110011110000101110", 27 => "10111100101110111000100000000001", 
    28 => "00111110011001110110101011111001", 29 => "10111101011001100100011011110001", 30 => "10111110000111000100011100011011", 31 => "10111101110000001000100001010001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

