-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_37_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_37_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101100101001001011010101011", 1 => "10111111010000111011011000010011", 2 => "10111101101010001011000000001000", 3 => "00111101011101011000011111010111", 
    4 => "10111101101000101100001000110111", 5 => "10111011101100110011010101001100", 6 => "10111101110000110010011111101110", 7 => "10111101100101101101111111000110", 
    8 => "10111101000001000011100100010101", 9 => "00111101001110100101011111101011", 10 => "00111100100000010011111011000100", 11 => "10111101011000000101101111000000", 
    12 => "00111101011101010101101011000000", 13 => "10111101111111111010110010100011", 14 => "00111110011111000100010000111001", 15 => "10111101110011110101110110111100", 
    16 => "10111100011001101000111000111111", 17 => "00111101100000101011100011000111", 18 => "00111101100101000001010010100101", 19 => "00111110111100111111100001110111", 
    20 => "10111101101011111100100000101010", 21 => "00111101110010101010011001001100", 22 => "10111100111101010001001001100110", 23 => "10111010010100011011011100010111", 
    24 => "10111101100001001010100000111011", 25 => "00111110001100000000111110111011", 26 => "10111101110000011100011010001111", 27 => "10111110010100101001000011101111", 
    28 => "00111101100000011100010110000010", 29 => "10111101101111000111001101101001", 30 => "10111110001111010100001101001010", 31 => "10111100001100111011001100100000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

