-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_114_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_114_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101001111100001100001101010", 1 => "00111100110001010011110100100001", 2 => "10111101011010111001100100001011", 3 => "10111011001100101101100100000110", 
    4 => "00111011110110111100011001100101", 5 => "10111100101010110110100011001111", 6 => "10111100000001010110000111010100", 7 => "00111101100100000110110101010000", 
    8 => "10111101010011011000101010011000", 9 => "00111101101111100010010011111111", 10 => "10111011111001010110100010100101", 11 => "00111100110100010000101100100000", 
    12 => "10111100101010110111101110101111", 13 => "10111100110110100100101011001111", 14 => "10111110011000010001111010000110", 15 => "00111011111010101010111100110110", 
    16 => "00111101010001000100101111110101", 17 => "00111101001001110110011001000001", 18 => "10111011110001110101110001001011", 19 => "10111100100001111000111110101100", 
    20 => "10111101000100100111000110111101", 21 => "10111101110110100101100001110001", 22 => "00111101000110000010010101011011", 23 => "10111100101011000100011100011011", 
    24 => "10111100001100010111000001010000", 25 => "00111101001111001110111010011110", 26 => "00111101100001001001000100101010", 27 => "10111101101100110101000000001001", 
    28 => "00111101000011011001100101000110", 29 => "10111101100110101111011011000111", 30 => "00111101001110111010100110001111", 31 => "10111100001000010001011001100110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

