-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_3_55_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_3_55_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110110000100000110001101011", 1 => "00111110000101001111101111011011", 2 => "00111101010101101101001010101010", 3 => "10111101110100011100110010010110", 
    4 => "10111101110100110011000000001110", 5 => "00111101111101110001001010100001", 6 => "00111101011111100001110010011011", 7 => "10111110001101110010101110001000", 
    8 => "00111111000010010101010011011010", 9 => "10111101011100100111011110000001", 10 => "10111101010101110100101101000000", 11 => "00111101000111001010111100101101", 
    12 => "00111101110010011110100010000001", 13 => "00111110011110111100110100110110", 14 => "00111101010101110110111111110100", 15 => "00111100101001100000100100010100", 
    16 => "10111101100000110010101110011001", 17 => "00111011000010000001111001000111", 18 => "00111110010010101110100100100101", 19 => "10111111001100000111000001110110", 
    20 => "00111101111000001101101010100001", 21 => "10111110100111000110000100001111", 22 => "00111101011000100011011011000001", 23 => "10111101100010111000110110000010", 
    24 => "10111110001100111010001001011001", 25 => "00111110001010111101110011110000", 26 => "10111100111000011011000010001010", 27 => "00111110101110100111110100100100", 
    28 => "10111101011110111011100101001001", 29 => "10111101100010010010100100100100", 30 => "10111101101101001101100010111010", 31 => "00111110100111100101100010000010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

