-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_15_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_15_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111111010110100000110110001000", 1 => "00111101110000010001110000101010", 2 => "00111111000001111011110001101111", 3 => "00111101100111101010000101000000", 
    4 => "10111111100001100001101100100010", 5 => "00111101111110001000101010001011", 6 => "10111101100101000111000011101011", 7 => "00111110110100000111001011110011", 
    8 => "00111101101101011111001011001011", 9 => "00111011100110001000000010010101", 10 => "00111100110011010110000110110011", 11 => "10111101110001000000001010001110", 
    12 => "10111101001101100110010000001010", 13 => "10111110000001100001000111111101", 14 => "10111101111111110000011011110111", 15 => "10111101111100111000100110110101", 
    16 => "10111111001110111001100010110111", 17 => "10111101000001010111110100011000", 18 => "00111101011101110010110101011110", 19 => "10111100101111010001011001110110", 
    20 => "10111110001110001001011111101010", 21 => "00111110100001111101100111011100", 22 => "00111110001101100100000001100100", 23 => "10111101000100101110100000111010", 
    24 => "00111100101001110110110110011000", 25 => "10111101101110111010000010100101", 26 => "00111111001110011000010011110101", 27 => "00111101110100010000101010011010", 
    28 => "10111110100011011101101100110100", 29 => "00111110110011001110100011011001", 30 => "10111101110111100110111101110010", 31 => "00111100110110001010011101100001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

