-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_10_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_10_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101101100101101000010100010", 1 => "10111011100110111000110010111001", 2 => "10111110001011101110010000011001", 3 => "00111101010100100001111111110011", 
    4 => "00111101100000111110010110111000", 5 => "00111101111001110011000011000110", 6 => "10111100101000001101100110010100", 7 => "10111100101001100111010000001000", 
    8 => "10111110110001110111000000010101", 9 => "10111101011110111001100111010100", 10 => "10111110101110100010100000010011", 11 => "10111100000111101111100101010101", 
    12 => "00111110110000110010001100110110", 13 => "00111101101111100110000101001010", 14 => "00111101001111101000110011001110", 15 => "00111110010001000010010101101100", 
    16 => "00111110101000000110010111111001", 17 => "10111100100011100001011100011010", 18 => "10111101101011011111100010110001", 19 => "00111101000000101110111011001000", 
    20 => "00111110100110010101100110100011", 21 => "00111101100110010100010000100100", 22 => "10111111001101100101101101010011", 23 => "10111100100101100010110011111110", 
    24 => "10111101101011101111110101000100", 25 => "00111101000100111000100010101001", 26 => "10111110011011000101110100100000", 27 => "10111111001000101110100010110000", 
    28 => "10111110101111100100011001001010", 29 => "10111101001000001010111110100011", 30 => "00111111001001000011101100001100", 31 => "10111101000110111111110011101011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

