-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_22_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_22_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110001010001101000011001100", 1 => "10111101111010001101000100001111", 2 => "00111101111011101000100101100101", 3 => "00111100101100101001101000011100", 
    4 => "00111101010111000010111000110100", 5 => "10111110000000111010011001001000", 6 => "00111101001011000110100010101001", 7 => "00111110110101010000001100010000", 
    8 => "10111101111100100101111001010111", 9 => "00111101100101011101101110111010", 10 => "10111101111111010100111110011100", 11 => "10111011100101101010101011010010", 
    12 => "10111101010101001010010011010011", 13 => "10111101101011100101101111001000", 14 => "10111101100011001100001001010000", 15 => "00111100100101101010110011101011", 
    16 => "10111110011001000000101011110010", 17 => "00111100001110100101000110100000", 18 => "10111101100100011100111100110101", 19 => "10111101110010110001001101011001", 
    20 => "10111101101101100001111011010110", 21 => "00111100000111010110111100010001", 22 => "00111100000111000010110000011011", 23 => "10111101001011010010111011011000", 
    24 => "10111101000100010011101001010000", 25 => "10111100101010111010000101101110", 26 => "00111101110101111101010000010111", 27 => "00111101110010000100101101011110", 
    28 => "10111101000010110001001001001101", 29 => "10111100111011101001100110100110", 30 => "10111100000010100100001110111011", 31 => "10111101100100110000010110010110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

