-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_28_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_28_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101100001000100000011110010", 1 => "00111101010010011101101111101100", 2 => "00111100110100001011101101101111", 3 => "00111101110101000101111110011110", 
    4 => "00111110001110010101100011011010", 5 => "00111100111111111000001000101100", 6 => "10111100101011101001110011001011", 7 => "00111101101010011011100111011000", 
    8 => "00111101100101110110101000101111", 9 => "10111101110101110011101001111001", 10 => "00111101110110011011111101011001", 11 => "00111101110000000001100000011110", 
    12 => "10111101110101101101100101111011", 13 => "10111011010110111011111000000001", 14 => "00111100111000110011000001010001", 15 => "10111100101111101111101011101000", 
    16 => "00111110101010100001100000010110", 17 => "10111101011111001000111000100110", 18 => "00111101111110111010010101011101", 19 => "00111110000111110101000011100011", 
    20 => "00111101111111111011111001110111", 21 => "00111101001110011010101011100111", 22 => "10111100001011001101000110000101", 23 => "10111101100110010100101101111011", 
    24 => "00111110011001010101101011000000", 25 => "00111110000000110001101011010010", 26 => "10111100010111000011011110100100", 27 => "00111101011010001110000111010110", 
    28 => "00111101111111010101111001001010", 29 => "00111101100010001111010111000011", 30 => "00111101010100011110001000010101", 31 => "00111101101010100000110010101110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

