-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_42_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_42_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101101000011101001010011110", 1 => "00111011101101101000010010001100", 2 => "10111101110110110101001000000000", 3 => "10111101000010100111000111011110", 
    4 => "00111101111001011010000111001011", 5 => "00111100101010101100001100100010", 6 => "10111101000100110011010011000110", 7 => "10111101101010110011010001100001", 
    8 => "10111101100100001110011101111001", 9 => "10111100111001110111011100001000", 10 => "10111101110010101101011010001000", 11 => "00111101100100100110110100000101", 
    12 => "10111101010010100110100101111011", 13 => "10111101101001011001011111010101", 14 => "10111101011111000001010010000011", 15 => "00111101101101000011000011110101", 
    16 => "00111101011011100010000000000100", 17 => "10111100101001101100010111010010", 18 => "00111101011001111001010101110000", 19 => "10111101110011001111011000111000", 
    20 => "10111101000000001110100111010101", 21 => "00111101010010101110010100110110", 22 => "00111100101101010111110001001110", 23 => "10111011100000001001010011100110", 
    24 => "00111101001010100001101001010000", 25 => "10111101110110011000011111000110", 26 => "10111101100101100001110101000011", 27 => "00111101011110000101010000000100", 
    28 => "10111101111101111000111101101001", 29 => "00111101100010110111011011110111", 30 => "00111101101101001101110001100110", 31 => "00111101001000011000000001001110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

