-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_0_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_0_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110011101100000001001000011", 1 => "10111101001000101000000000101000", 2 => "10111101101000010000010100011000", 3 => "10111101000000001000111110101000", 
    4 => "10111010111011100010100001100111", 5 => "00111110001100110011100000101110", 6 => "00111011100110001010001000100011", 7 => "10111100111001000011000000101011", 
    8 => "00111101100011011011011000011100", 9 => "10111101111000110110111000101111", 10 => "10111101011100011010101100001000", 11 => "10111101101100111110110101010010", 
    12 => "10111101101011100111110101010110", 13 => "00111100111011100010001000011101", 14 => "00111100000101111001100111100101", 15 => "10111101000110000110000000010011", 
    16 => "00111101010100110111001010100100", 17 => "00111011100011110001000010101010", 18 => "10111100110111010011000100110011", 19 => "00111101001110111010110010110100", 
    20 => "00111100110001111111101110101101", 21 => "10111100111101011111011011111101", 22 => "00111101011011011101110111110100", 23 => "10111101101001011101100101011110", 
    24 => "10111101001111100101101110000101", 25 => "10111100011100100110011010111010", 26 => "00111101010100011111101101000000", 27 => "00111101011011000110101111001111", 
    28 => "00111101101101011011110001000101", 29 => "10111011011011100001011110100000", 30 => "00111101100111100010000101010011", 31 => "00111100000010001011000100010100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

