-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_14_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_14_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110011101110111001001010000", 1 => "10111100101001110010110010010101", 2 => "00111101010110000011110101111001", 3 => "00111100011000011001011101011111", 
    4 => "00111110000101111110001000111111", 5 => "00111101110001011100100000010001", 6 => "00111100000001000011110000111010", 7 => "00111101001001101110101010000101", 
    8 => "00111101010111100010010110000101", 9 => "10111101101100111000010001110111", 10 => "10111101001000010001010101011001", 11 => "00111101011000100101111010011010", 
    12 => "00111100101001111001110111010100", 13 => "00111011101011101001011010000001", 14 => "10111101100011110100000111110010", 15 => "10111101010100011010000000000110", 
    16 => "10111101011001110100110100010110", 17 => "10111101001010101110111000100000", 18 => "10111101101010101001100100110001", 19 => "00111101100001010111100011100110", 
    20 => "10111101011000100100111011011111", 21 => "10111101010010110110101001100010", 22 => "10111100000010100001010110011000", 23 => "10111101100001000100111110100000", 
    24 => "00111101100011010111101111101010", 25 => "00111110001101011001101011111010", 26 => "00111011110001000001110111010010", 27 => "00111101110010011110000010100100", 
    28 => "00111110010110110000001101011100", 29 => "10111100110001010110000011001000", 30 => "00111100010011111101100011110001", 31 => "00111110001101101000001000110000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

