-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_63_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_63_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101000100001101111100010110", 1 => "00111101011000000001000101001101", 2 => "00111100111010011001100001001010", 3 => "00111101010100000110101110111110", 
    4 => "00111100001100100110011111000111", 5 => "00111011001111110111111100000110", 6 => "10111101101000001011100100010011", 7 => "00111101011100010000100110001101", 
    8 => "00111100111110000001111010001010", 9 => "10111101001000111110001010010011", 10 => "00111100010000010010101011011000", 11 => "00111100111001111010101101110101", 
    12 => "00111101000010111110011000011101", 13 => "10111010101111000011100000101010", 14 => "00111101100010110100010100101000", 15 => "10111101000101011010000110001000", 
    16 => "00111011110110110010011100000011", 17 => "10111100110100011010001000011111", 18 => "10111101100111000011100000101010", 19 => "00111100100000011111010100111000", 
    20 => "10111101000111000001001111111101", 21 => "00111101001100100100011101000101", 22 => "10111101000001010011010010111101", 23 => "00111100011001001000000111110101", 
    24 => "10111101100111100110111011101011", 25 => "00111101100111001010001010011000", 26 => "00111100100001110001100000100010", 27 => "00111101010110001111101000110111", 
    28 => "10111101101011000100110111101100", 29 => "10111101000101010010011011011001", 30 => "10111100100011110001010011011011", 31 => "10111101011010110101110101000110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

