-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_42_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_42_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110101110000011110110011011", 1 => "10111100111101100011110000110010", 2 => "00111101101000110000010001000111", 3 => "10111100001110111110100001111001", 
    4 => "00111101110111001010101001110110", 5 => "00111110101011110010110011111001", 6 => "00111101001100011000111111000101", 7 => "00111101101011011011110011101101", 
    8 => "00111110001011001010000001111111", 9 => "00111101101001111110000001101001", 10 => "00111101110000110110010111001011", 11 => "00111101100111010100111100010110", 
    12 => "00111101001000000011000111001111", 13 => "10111101101101001001000011100110", 14 => "10111101011111110111010010001010", 15 => "10111101011000111100101001110101", 
    16 => "00111101001001001111111111001001", 17 => "00111011100110000101011010100011", 18 => "10111101110101000110001111010000", 19 => "00111100000001010011001110110001", 
    20 => "00111101001011111111010111000111", 21 => "10111100111101110001011001001100", 22 => "00111100111000000111100000010000", 23 => "10111100101010001011100011110001", 
    24 => "00111101001101010000001110111000", 25 => "00111101100110001001101011001100", 26 => "00111110001100011010110110100111", 27 => "00111100100110010101001001001100", 
    28 => "00111101001100010010001010111000", 29 => "00111100111110101101000010000001", 30 => "00111101110010100011001101111011", 31 => "00111101101010011110110111000000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

