-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_3_31_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_3_31_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110100100001000000101011110", 1 => "10111101100110101011101100000010", 2 => "10111100101010100110101100001110", 3 => "10111101111110101110101100111110", 
    4 => "10111101101100111001101001111100", 5 => "00111101100001101001111100000110", 6 => "10111101100001110000011001001111", 7 => "10111110001111111110011011010110", 
    8 => "00111100110100100100100111100100", 9 => "10111100110110101000001101101111", 10 => "10111101110000011110000111010010", 11 => "00111101101111011110000101011101", 
    12 => "10111100100010111001110111000011", 13 => "10111101111110110110011001110011", 14 => "00111101100101010100001110101111", 15 => "10111101101101011100100001010100", 
    16 => "10111110000010011011111110011100", 17 => "00111101011000110111100110110111", 18 => "00111110011101111001000110000010", 19 => "10111101100001101111011000001110", 
    20 => "10111101110001010100101000111100", 21 => "10111101010110100001001000110000", 22 => "10111101000111111111110001010100", 23 => "10111101110000110101011010010111", 
    24 => "00111101001011010101101011100010", 25 => "00111110100000010110010011000111", 26 => "00111101100111111011000111100010", 27 => "00111110011000000010101111000111", 
    28 => "10111100110100100111001111010110", 29 => "10111101110100011000101100001101", 30 => "00111101011011110100101011011100", 31 => "00111011011110110000000010111101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

