-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_3_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_3_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110000101101011000001010011", 1 => "00111101010000111010001000010110", 2 => "10111110101010111110111001011111", 3 => "00111101110000100100111111101100", 
    4 => "10111100010001011111011111000110", 5 => "00111101100110011110001110000110", 6 => "10111110100010011011000010101011", 7 => "00111101111111101000010101110111", 
    8 => "10111100000101011011101110111111", 9 => "00111101110001100011011010110001", 10 => "00111101100010000110010110010101", 11 => "10111101111001000011110000111010", 
    12 => "10111101110110011000001110010100", 13 => "10111101100110110011111000010100", 14 => "10111101110011001100011110001111", 15 => "00111101100111000001011010011100", 
    16 => "00111110000000100010100100100000", 17 => "00111101100001101000001111000011", 18 => "10111101101101101010101011010010", 19 => "00111101110111101010110011001001", 
    20 => "00111101111000001010001000000001", 21 => "10111101001011001110111111101101", 22 => "00111101110010001011101100001010", 23 => "00111101101011111111100101110010", 
    24 => "10111010100011101011110011000111", 25 => "10111101011000111000100001100110", 26 => "10111101111100111101001000001111", 27 => "10111101111001111000011000111100", 
    28 => "00111101101110000101111100000111", 29 => "10111101111011011111110011100011", 30 => "00111101011011101011011100000010", 31 => "10111101101001100011101001011100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

