-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_111_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_111_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111100000000011110100010100011", 1 => "10111101001010010000001101100100", 2 => "10111100011001010001000010010000", 3 => "10111101011100011111011110010100", 
    4 => "00111110010111110100111100001110", 5 => "00111101011001101011110001100010", 6 => "10111101001100001101000111111010", 7 => "10111101000011100111000101000111", 
    8 => "00111111001100100011000111101000", 9 => "10111101101110101111110000000101", 10 => "00111110100110111111011001111111", 11 => "10111101010111010001110000111011", 
    12 => "00111110010010100100001011110010", 13 => "10111111101011010100000110100111", 14 => "00111110110011001110110110010001", 15 => "00111111111101100101010010010011", 
    16 => "00111110101110100100011001111100", 17 => "10111101100010000101101110011111", 18 => "00111111000010011001101100001011", 19 => "10111100110110101110101000110001", 
    20 => "00111100011101110111001010010011", 21 => "10111101100001010000110011100101", 22 => "00111110000111001001100001011111", 23 => "00111100010111010000100101011011", 
    24 => "10111010011100000001111110111000", 25 => "00111101001011111010100000101111", 26 => "00111111101000110011001000111000", 27 => "00111110011001101111110011011111", 
    28 => "00111111000000000010000100101001", 29 => "10111101100010011110110100111001", 30 => "00111110101111010111111000100100", 31 => "00111101110011100000010101000111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

