-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_72_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_72_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111111000000011010000101010101", 1 => "10111111010010100111010101111001", 2 => "10111110100001001101101001101110", 3 => "00111100001100110110101111010011", 
    4 => "10111101001101111100011001110110", 5 => "10111011011010100010100011111110", 6 => "10111110000111011011111110001100", 7 => "00111100001011011110001000100110", 
    8 => "10111101001100101110001110000010", 9 => "00111110000001000110010110100101", 10 => "10111101011001111011101100110000", 11 => "10111010101111100010111101111011", 
    12 => "10111101101011000010100000101100", 13 => "10111101101111011101101100010010", 14 => "10111111010101000001110000111111", 15 => "00111101100010101110111110110011", 
    16 => "10111101011011101000000001111100", 17 => "00111011011111011111001110110110", 18 => "00111011001000001111010011011000", 19 => "00111101100101001011110011110001", 
    20 => "00111110010000111001011001001010", 21 => "10111101110011100100111110111001", 22 => "10111101100001101111000111011100", 23 => "00111101101100100010110100001110", 
    24 => "10111101001011110100101111101000", 25 => "00111101111001100001110100000000", 26 => "00111101011101110000110111101001", 27 => "10111101010101000111100011001000", 
    28 => "00111110011011010000001011001101", 29 => "00111101100010000000010110100011", 30 => "00111011110001011011000001111001", 31 => "00111100100100101100000001100010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

