-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l1_p_ZL2W1_0_1_RAM_1P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l1_p_ZL2W1_0_1_RAM_1P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111110111110010001000110101110", 1 => "00111110010011001000010010110110", 2 => "10111110011100011110111111111010", 3 => "00111110011000011000001111111001", 
    4 => "10111101101111000111111101111000", 5 => "10111110111011111010110100001000", 6 => "00111110100001110100110101011001", 7 => "00111110001110001010010110001011", 
    8 => "10111110111010111011001000010100", 9 => "00111100001011101001011010000001", 10 => "10111110111111111110011010010010", 11 => "00111100010010111001001000111010", 
    12 => "10111101001011000101001010100100", 13 => "00111101101011010110000110110011", 14 => "10111110101010100101110010000001", 15 => "10111100110101100001000010101110", 
    16 => "10111101010011100110000110001101", 17 => "00111110010100110111010111001001", 18 => "10111110011100001111011101110111", 19 => "10111110100110011010100011001110", 
    20 => "10111110100001010100101000111100", 21 => "00111110101010111110100101000010", 22 => "10111110110011101000010110011000", 23 => "10111110110000001110100010000110", 
    24 => "00111110110100011001101111010100", 25 => "00111101100111111111110001010100", 26 => "00111110101110101000100110111001", 27 => "10111110100110000110010011101101", 
    28 => "10111110100010010110111101000100", 29 => "00111110110100110111100111111011", 30 => "10111110111110100010001110011110", 31 => "00111110100001001011010001001010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

