-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_87_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_87_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101100001000100111010010100", 1 => "00111101001100001000001001001001", 2 => "10111101001001111010010000011110", 3 => "10111101001010001011011111100101", 
    4 => "10111101011111110011010010010100", 5 => "00111101001100001011101011101001", 6 => "10111101001101000000001011010001", 7 => "10111101101100011000110110101100", 
    8 => "00111100100101011111010001011110", 9 => "00111100100111011000011000100011", 10 => "10111101110101011001100110101010", 11 => "00111101100101100000011010111000", 
    12 => "00111100101000111011011110010101", 13 => "10111101011010110001101000101010", 14 => "10111101011101100111000110101100", 15 => "10111101100001010010101111010100", 
    16 => "00111101001111100111001110100011", 17 => "00111101000011001010000111001111", 18 => "10111110001001001011110010101110", 19 => "00111101001100111100110001001011", 
    20 => "10111100011011100111001111100111", 21 => "10111101101111111000010111010111", 22 => "00111101100001001101100110000100", 23 => "00111100100001011000111111110111", 
    24 => "10111101011000000010010100111001", 25 => "10111101100100000001001100100011", 26 => "00111101000010111000011110111110", 27 => "10111100110000101010111011010001", 
    28 => "00111101010110001100101100001000", 29 => "10111101001100101011000000100001", 30 => "00111100111100011100100101110001", 31 => "00111100101011101110111010010101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

