-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_24_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_24_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111100101000110001000111101000", 1 => "10111101011111011101111111001010", 2 => "00111101010110010011110001000111", 3 => "10111100011001100111110101111000", 
    4 => "10111101111101001001101111101001", 5 => "00111100101110110000001111100010", 6 => "10111110000011001011011011001000", 7 => "00111100110110100011101000001000", 
    8 => "00111101011010011110100100001000", 9 => "00111101011100011000010101001001", 10 => "10111101110110100101100011110111", 11 => "10111101000011101000110010001011", 
    12 => "00111011110101111111100101010001", 13 => "10111101111110000011110011110011", 14 => "00111101100111000011010110001011", 15 => "10111101010011110011011001101001", 
    16 => "10111101010110011001100110011010", 17 => "00111100001001101010010001000100", 18 => "10111101110100101001001111010001", 19 => "10111100110001000011000010110001", 
    20 => "10111101100111000110110010011000", 21 => "10111101001010000000100011001000", 22 => "10111101111110010010110110011001", 23 => "00111101100100010110000000001111", 
    24 => "10111100101011010001101011101011", 25 => "00111110000000001000011000111000", 26 => "00111101100011011011110011101101", 27 => "00111101100110101000101101001100", 
    28 => "00111100010000001011000100110110", 29 => "00111100111011000101001010100100", 30 => "10111100100110001101101011000010", 31 => "10111101111101010000010011000101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

