-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_77_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_77_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111100101010100101101001000111", 1 => "10111101111111111101110111101100", 2 => "00111010011111011100000101100001", 3 => "10111100000001100101010100011001", 
    4 => "00111101101111101110001101010000", 5 => "10111100011011001011111110110001", 6 => "00111110100000010100001110111111", 7 => "00111101001000001101111111011111", 
    8 => "10111110000011001011000011000000", 9 => "10111100110000010111011001010111", 10 => "10111101010110100110010100000110", 11 => "10111100111011100011011100010101", 
    12 => "10111101101111010111101100100000", 13 => "10111110101101000010111111101000", 14 => "10111101100111100000010110001010", 15 => "00111101111110110000111011100101", 
    16 => "00111110100011000001010101001101", 17 => "10111101101110110001111110101100", 18 => "10111111001100101100111010001001", 19 => "10111101011101011101110011000110", 
    20 => "10111101101000110011000001010001", 21 => "10111101111011001011111100101011", 22 => "00111110011011010010010100100100", 23 => "10111100001110000011000001011110", 
    24 => "10111101101110010111011011111111", 25 => "00111110011000101111101010010100", 26 => "10111110100001000001001001001001", 27 => "00111110010000111101001101011111", 
    28 => "10111101111001011110000100111011", 29 => "00111110100011111011101000100011", 30 => "10111110111011100101110001110000", 31 => "00111101101000110111100100110001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

