-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_15_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_15_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111100111101010011110001011000", 1 => "00111101100011101000111110110000", 2 => "00111100001010011001111110100001", 3 => "10111101011000011001111111000011", 
    4 => "10111100110011111100101001000011", 5 => "10111101011001000100111010010100", 6 => "10111101010111100010010001111001", 7 => "00111101100110010001100100100110", 
    8 => "10111101100011100000100001101100", 9 => "10111101001111100001001100101011", 10 => "00111100111100000110000010111011", 11 => "00111101100101001011101111100100", 
    12 => "10111100010000000011011110010011", 13 => "10111101100100111110101111000000", 14 => "00111101011101001011110001101010", 15 => "10111101010001000110110001110110", 
    16 => "00111101101000101110010101011000", 17 => "10111001111111111101101001000000", 18 => "00111101100011100101110011010101", 19 => "00111101101011000011101000000000", 
    20 => "00111100110011001110111001011011", 21 => "10111101100000010110110011101000", 22 => "10111101000110101111001010010101", 23 => "00111101011000001100100011001101", 
    24 => "00111101010101011010010110111001", 25 => "00111010101101000001011111001010", 26 => "00111101100111101001011011000100", 27 => "00111101100111010010111000001110", 
    28 => "10111101101000101100011101110101", 29 => "10111011100100000100011100001011", 30 => "10111100101000110110010111001011", 31 => "00111101000001010100010001111000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

