-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_56_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_56_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101111011001010000000111100", 1 => "00111011101001011100111001011011", 2 => "00111101101110110000101010110011", 3 => "00111100000100100011010111111000", 
    4 => "00111101101010001100010110000111", 5 => "00111101010010110010100101011111", 6 => "10111101000010111010001100000001", 7 => "00111101110110001011111001110011", 
    8 => "00111110000000100111011111000100", 9 => "10111101011101101101000000001011", 10 => "10111101000101011110001110010111", 11 => "10111101110001101100110010100011", 
    12 => "00111101110001100110100100000101", 13 => "00111100011110010111001001000111", 14 => "00111100110001011110001011001110", 15 => "00111101111010001000110101101101", 
    16 => "00111110100101101111100100110011", 17 => "00111101110000010100100000110100", 18 => "10111101100000010001010011010011", 19 => "00111110010011011000000110101110", 
    20 => "10111011000111010000011000110110", 21 => "00111011100011011100100110000010", 22 => "00111100011000101000101010100100", 23 => "00111101001111000101110111101010", 
    24 => "00111110100011110100011001100111", 25 => "00111101001010010001000100000110", 26 => "10111101000000101011010000001111", 27 => "00111101101000010001001111000111", 
    28 => "10111100010000010000110101111100", 29 => "00111110011011110100011111111010", 30 => "10111101111011011010110100110010", 31 => "10111101101011001001101011111110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

