-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_60_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_60_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101100010110001111001011100", 1 => "10111101111100111001011101010111", 2 => "10111101110110111000000100110000", 3 => "10111110010011001001101010111011", 
    4 => "00111110110111110110111000011110", 5 => "10111101110011111010001101110111", 6 => "10111110100001001100101001110001", 7 => "00111101011011110100000001011111", 
    8 => "10111101111001010100010011111110", 9 => "10111110011101000000001011010001", 10 => "10111101000100100100000001110100", 11 => "00111110001000001110111000000111", 
    12 => "00111101110110111100111111010101", 13 => "10111100111110000001100001000000", 14 => "00111101010110100011000010011000", 15 => "00111101110110111100110000101001", 
    16 => "00111110010110101010110010010111", 17 => "10111100011000100101010000011110", 18 => "10111101011110011110111000000011", 19 => "10111101001010011011000101110101", 
    20 => "10111111000011101101000111110010", 21 => "00111100010111110111101001001110", 22 => "10111100011001101101010110001101", 23 => "10111110001001010011110111101010", 
    24 => "00111110010110000110101111011111", 25 => "10111100010100101110000011100011", 26 => "10111011011001000110010010011001", 27 => "10111101111110010000001110100111", 
    28 => "10111110001001011100100101100000", 29 => "10111101000010000000111010001101", 30 => "00111101111000001000111100100001", 31 => "10111110000010010001100100100110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

