-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_3_33_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_3_33_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101100000000110001000001011", 1 => "10111110000101001000011000100111", 2 => "10111101110101100010100011001100", 3 => "00111101010110110011100011010110", 
    4 => "00111100100010010111100001001111", 5 => "10111101010010010001110100010101", 6 => "00111101100110110110100110011000", 7 => "00111110010110100110011101100010", 
    8 => "10111110001001100001111100011001", 9 => "10111011111110010011001101011101", 10 => "10111101100010010011000001111011", 11 => "00111011100011000100011110100001", 
    12 => "10111101110000010001010001001101", 13 => "00111101011011111101001000100000", 14 => "10111100111000010101110010100111", 15 => "00111101100000111110011000111111", 
    16 => "00111101011011101001000101000011", 17 => "10111101101110001100000010001011", 18 => "10111110010010000111011010011111", 19 => "10111101101011100101011100010001", 
    20 => "10111101001001011011001100011000", 21 => "10111110000110001011011001010010", 22 => "00111101001111001001110111100000", 23 => "10111101011000110011110111110011", 
    24 => "00111100111001010101010111000101", 25 => "10111101110101100001110010111101", 26 => "10111100110100111001010100111110", 27 => "10111110001100010101000101100001", 
    28 => "00111101100010001100011100011001", 29 => "10111101101110000101011010100011", 30 => "00111100010101011011111011100100", 31 => "10111101010111001110011111001101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

