-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_8_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_8_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111011110100110100000101011011", 1 => "10111101000011001011111000011111", 2 => "10111101101011011000100100000101", 3 => "10111101011000011000010001111111", 
    4 => "10111101101000010010011110110011", 5 => "00111011011001000111010101100000", 6 => "00111100100011110000101001011111", 7 => "10111101011110101001010010111100", 
    8 => "10111100101001100000100100010100", 9 => "10111101100010110100011101000001", 10 => "00111101000000101110111111010100", 11 => "10111100110011110110110111111100", 
    12 => "10111101100101101000111110001110", 13 => "10111011111010011110111001000110", 14 => "10111101101011110001110000110010", 15 => "00111100101011110111011011100110", 
    16 => "10111101100110000001100011000110", 17 => "00111101100101110000011100011000", 18 => "10111101001011011010100110000110", 19 => "10111101011101101100000001010001", 
    20 => "00111101100110010100011000111101", 21 => "10111100001100111001111000101000", 22 => "10111101000101111011010100101000", 23 => "10111101001011110101001100111111", 
    24 => "10111011100010001010010001111111", 25 => "10111011110111101101001010001001", 26 => "00111101011010100100000000010000", 27 => "00111101100001000101100110010110", 
    28 => "10111100111001010111110110011110", 29 => "00111101001000011000010001111111", 30 => "00111101100101001100101010010010", 31 => "00111011100010100010011001011111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

