-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_9_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_9_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101010001011010010111111100", 1 => "10111101011111000100100011110001", 2 => "10111101101010101010101001111110", 3 => "10111100101100100110111000010001", 
    4 => "10111101101101010110001000010111", 5 => "00111100110110001011111001110011", 6 => "00111101101011011100101000001000", 7 => "10111101111101000100011011111010", 
    8 => "00111100100111001111100110100000", 9 => "00111101101001100100001000111001", 10 => "10111100100001101101010100000110", 11 => "10111101110010010100101100111000", 
    12 => "00111101111101101101000000001011", 13 => "10111101010111101000010011110001", 14 => "10111100000101110001011111011111", 15 => "00111101101110011100111000000111", 
    16 => "10111101110011101111111111100011", 17 => "00111101111110000001101101100101", 18 => "10111101011011100011000011001011", 19 => "00111110000001010000101111011000", 
    20 => "10111101101010101011000111010101", 21 => "00111101111111001011011010000101", 22 => "10111101010000101101001110000100", 23 => "10111101111001111010010010100101", 
    24 => "10111101101011000111111010101110", 25 => "10111101110100001101010010011001", 26 => "00111100010111010101110100111110", 27 => "10111101100101101001010111011001", 
    28 => "10111101010000001111100110010000", 29 => "10111101110101101000010000000110", 30 => "10111101110111101110100010001110", 31 => "00111011100001011001100001011011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

