-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_50_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_50_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111011111110111011100101001001", 1 => "10111110010000111101001000001111", 2 => "10111100100011001111101111111100", 3 => "00111110001010110110110110000111", 
    4 => "00111100101000111001110001010010", 5 => "10111100110110110111010010011011", 6 => "00111101100111001101001101011011", 7 => "10111100101110011100011100110111", 
    8 => "00111100111000100110110101001000", 9 => "10111110111100100000111000011111", 10 => "00111101010100011110001100100010", 11 => "10111101111010001111010010110110", 
    12 => "10111101110001000010111100011111", 13 => "10111101011011101101110111001110", 14 => "00111110100010101011100001100011", 15 => "00111101011101111110111001001110", 
    16 => "10111101000101001101000011011101", 17 => "10111101011011111011001110110111", 18 => "00111101101000111101111101101110", 19 => "10111111001101001100010100110011", 
    20 => "10111101001011010000111001010110", 21 => "10111110000001010001011111100111", 22 => "00111101011000110100100001101111", 23 => "00111100100111011010000101100110", 
    24 => "10111010100111110100000010100011", 25 => "10111110100100010011000001011001", 26 => "10111101011001111101111011010111", 27 => "00111110111011011111000011110110", 
    28 => "10111101011101000111111010001101", 29 => "10111101010110010010000100000100", 30 => "00111110100101010010110100100011", 31 => "00111101010011010001110110001010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

