-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_75_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_75_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101100101001101010000000010", 1 => "00111110111110010100010011001100", 2 => "00111110100101011000011001000100", 3 => "10111101001010100110100011110101", 
    4 => "10111110010110110010010111110110", 5 => "00111101111100110010100010110111", 6 => "10111101001010110100111010011000", 7 => "10111101100101011110010000011101", 
    8 => "10111101011001011010101111000001", 9 => "10111101101000001110111000000111", 10 => "00111110100100011101111101010101", 11 => "10111101100010110100110001111111", 
    12 => "00111100111101100111000010100000", 13 => "10111101001110000010011111111010", 14 => "00111110100110101111010111011100", 15 => "10111110101011010011001111110100", 
    16 => "10111110001101100111110011110010", 17 => "10111101101000100110001101010010", 18 => "10111101111000100101001100010001", 19 => "00111101100010101011011010001101", 
    20 => "00111110100011100111100110101011", 21 => "10111101110001111011011001111000", 22 => "10111101011110011110011110111000", 23 => "00111101010111000011101011001001", 
    24 => "00111100100001010011010111001010", 25 => "00111110101100111111101010110001", 26 => "10111110010001101111010110001000", 27 => "10111110111011110011011101010100", 
    28 => "00111101100110110001011000111100", 29 => "10111101111100000011000110001100", 30 => "10111101001101010001000001001101", 31 => "10111110000110110110010110101010");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

