-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_3_0_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_3_0_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101011001000011111011011001", 1 => "10111100110101000111011110111100", 2 => "00111100101111010100111100010110", 3 => "00111101001001100011010000010001", 
    4 => "00111101010101001100100110000110", 5 => "00111100011001101010011101101001", 6 => "00111101100000011110111011101110", 7 => "10111100111000111000101001111110", 
    8 => "00111100101000100110101000100011", 9 => "00111101110111011100101101011000", 10 => "10111101101110000101110111111011", 11 => "10111100110010000000010000010000", 
    12 => "00111101101011110111000010011011", 13 => "00111101101111110010101110101010", 14 => "00111101001101011000110000001001", 15 => "10111101110110110100110111001111", 
    16 => "00111101010100010000111001000101", 17 => "00111011111001001100100101000011", 18 => "10111100101001111010110010000010", 19 => "00111101111111010101000010101001", 
    20 => "00111101101000101001010110100111", 21 => "00111101111110001111000101001110", 22 => "10111101100100111111101001101110", 23 => "00111101000011011111010110001100", 
    24 => "00111101111110011101000100101101", 25 => "10111101101010110011011001111010", 26 => "10111101111011100011000011001011", 27 => "10111101101011000100110001011001", 
    28 => "00111101111101011000010100111000", 29 => "10111101110011000001110010100100", 30 => "10111100001010101001001011100110", 31 => "00111101101001001011011101101111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

