-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_51_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_51_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110001101000111101010011110", 1 => "00111101010001111100001100001101", 2 => "00111100101000001001111011011100", 3 => "10111101101100110001110010101000", 
    4 => "10111100100100110101001100101110", 5 => "00111110011000000010110011010100", 6 => "10111100000101100110101111101000", 7 => "10111101001111001110010100101110", 
    8 => "00111101110000000000100011101010", 9 => "10111101101001000110110110000011", 10 => "00111101001111100111110100010011", 11 => "00111011111000001011000010101111", 
    12 => "10111101101001101000110000100110", 13 => "10111100100101011001101000110001", 14 => "00111011100001011000111111110111", 15 => "10111101100000111000011111011111", 
    16 => "00111100100101110000110101100011", 17 => "00111100111001100110000000011100", 18 => "10111101101000000101100000010101", 19 => "10111100111111011110110101101100", 
    20 => "00111100110011111110101111010001", 21 => "00111101001100111010101111001001", 22 => "00111101000010110000111000011011", 23 => "10111101011111110011101011011110", 
    24 => "10111101001010000101011001100000", 25 => "00111011110011001111011010111110", 26 => "10111100100011010110001010111111", 27 => "10111101001101011011011100000111", 
    28 => "00111110011110000000001101000111", 29 => "10111101101111001000010111000010", 30 => "00111101001011000110101111001111", 31 => "00111101101110110011000101111111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

