-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_0_28_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_0_28_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110000101010100010000110101", 1 => "00111100000001000100010010011110", 2 => "10111101101111101100101010101100", 3 => "00111101111110110101000001101110", 
    4 => "00111101110010000010010010010010", 5 => "00111110000100101100111110010110", 6 => "00111110001011100001000011001111", 7 => "00111101110111001111110001000000", 
    8 => "00111101110110100010001101111101", 9 => "00111110000111111110011000001100", 10 => "00111101000011001100001101011101", 11 => "00111101011101011111101000100010", 
    12 => "00111101100100100000010110111100", 13 => "00111110011010111001100011001000", 14 => "10111110000011110100111011001010", 15 => "10111101010100100000001110100011", 
    16 => "10111101010010111111110100101111", 17 => "00111100011000010000000001100000", 18 => "10111101111010101000110110101000", 19 => "10111100010001110101110001001011", 
    20 => "00111100110011110000010100100001", 21 => "10111101100011010101100101001111", 22 => "00111110000111011001011001100100", 23 => "10111101000100010110001100110101", 
    24 => "00111110010001010011100011101111", 25 => "10111101010011010100011101111100", 26 => "00111101000010110101011110000010", 27 => "10111101101010110100100101011010", 
    28 => "10111101110111001000011111011011", 29 => "10111100110110110111110011111110", 30 => "10111100111111101100011110000110", 31 => "00111101010110010011010011110000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

