-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_1_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_1_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101111100011011011110011110", 1 => "10111101011011101100001010001011", 2 => "10111101000011001001100101101011", 3 => "00111101110011100110001010011001", 
    4 => "10111110000001000010000011110111", 5 => "10111110000011011000111010000110", 6 => "10111101100110000111101011010001", 7 => "10111101110000110100001100110001", 
    8 => "10111101111010010000000101001011", 9 => "00111101100001011100000010111010", 10 => "10111101100010101011110001010001", 11 => "00111011011001100101101111101010", 
    12 => "00111101010000001111111111011010", 13 => "10111101001111000011001111111000", 14 => "10111101001110111001000101110001", 15 => "10111110000100001010100101011000", 
    16 => "10111110000000110101011111100110", 17 => "00111101010010101111001011011000", 18 => "00111100101001010100011000001011", 19 => "00111101010000100001001010010100", 
    20 => "00111100111101110101101110000001", 21 => "00111100100000101110001000110011", 22 => "00111101100101100100010010010101", 23 => "10111101110101010101000011001010", 
    24 => "00111011100011011101101001001001", 25 => "00111100100101101010001001101110", 26 => "00111101100111110011011100110011", 27 => "10111101100010101001000001000111", 
    28 => "10111101001110111110100001111001", 29 => "10111101110000000100100101100110", 30 => "00111101011100101101000110101111", 31 => "10111101100100101011111001001001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

