-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_43_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_43_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101000000001001011011111111", 1 => "10111100100110101101100001011110", 2 => "10111100111111000111111001101011", 3 => "00111101001000010001000000011011", 
    4 => "10111110000110101111101001110010", 5 => "10111101000001000001000000110000", 6 => "10111101010001011010001111100100", 7 => "00111101000111000001011100100010", 
    8 => "10111101011010100110111100111111", 9 => "00111101100101111110011101111101", 10 => "00111101000111000110011011010011", 11 => "10111100110000010001110000101010", 
    12 => "10111101000110010111101000100101", 13 => "10111101110101010000000110011111", 14 => "10111101010000101110001100111111", 15 => "00111101101100111000110001010100", 
    16 => "00111101001111011101010001000001", 17 => "10111101010110011000011010111010", 18 => "10111110000001110110011100001010", 19 => "10111101011001101011110001100010", 
    20 => "00111101000101001011001110000001", 21 => "00111100110101100000010000011001", 22 => "00111101110011101100101111111011", 23 => "10111101101010110111100110010110", 
    24 => "00111101101101010001010110001100", 25 => "10111101111101000011111100011100", 26 => "00111101100001111001110011000111", 27 => "00111101011010001111101100000001", 
    28 => "00111101110000101101001011111110", 29 => "10111100100001010001001000100011", 30 => "10111101111101011001100100100100", 31 => "10111101000000110010001000101001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

