-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_1_25_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_1_25_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101011100011011011110011110", 1 => "10111110001100001011001101001110", 2 => "00111100001011001001101011111110", 3 => "10111110000010101001001110101111", 
    4 => "00111110010001111000101101111010", 5 => "10111100110010101001100010101011", 6 => "00111110001000000101000001111010", 7 => "10111100100001010000100111000000", 
    8 => "00111101010011101101100000001010", 9 => "10111110100111101010011010100000", 10 => "00111011110100110100100110111111", 11 => "10111101110000111011001101100011", 
    12 => "10111100001010111001011011110010", 13 => "00111101101101100110100000111100", 14 => "00111110100101001001011011101110", 15 => "10111101111000001111000000100000", 
    16 => "00111100100101100011011101111010", 17 => "00111100111010100110110000011010", 18 => "00111101100110011001100010001101", 19 => "10111110100100110110110000010110", 
    20 => "00111101000110010110001000000111", 21 => "10111110011100011001001000100001", 22 => "10111100011010001111111100110010", 23 => "00111101101101111001101001101011", 
    24 => "10111101000001101001100000110101", 25 => "10111110010111010110110100111011", 26 => "00111101101110110100001111011001", 27 => "00111101000110001110101110001001", 
    28 => "00111101010101010100110010011000", 29 => "00111101011010100111010001111110", 30 => "10111110100001100010000110111000", 31 => "10111101100110111010100110001111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

