-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_33_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_33_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110001101011100010011101011", 1 => "00111110000100010000101000010011", 2 => "00111101110110010011111011100110", 3 => "00111101111011010111100111010001", 
    4 => "00111101011000110011110011100110", 5 => "00111101010110101010111001101101", 6 => "00111110000100100100100001010010", 7 => "10111101000110110111101111110010", 
    8 => "00111110000110000000001100000100", 9 => "00111101111010000100100101000101", 10 => "10111100100001110011011110010111", 11 => "10111011110000001000101101110110", 
    12 => "00111101110001001100111010000001", 13 => "10111101000101010010000110011011", 14 => "10111100011000001110101101101000", 15 => "00111100001010111000111010001111", 
    16 => "10111101010001011100011110001010", 17 => "10111101001000000111000010111001", 18 => "10111101011010000111010011001001", 19 => "00111110000010000000000100101110", 
    20 => "10111011111000111111011110001100", 21 => "10111001100010110111010111101010", 22 => "10111100110110110101000011110100", 23 => "00111101010011100000000100010101", 
    24 => "10111101101111110111011010100011", 25 => "00111101011111100100010001110100", 26 => "10111100010110100100000001010011", 27 => "00111101100001001101100011111101", 
    28 => "00111110000101101001011010100010", 29 => "00111101011001110001101011000001", 30 => "00111101000110101010001011100100", 31 => "00111101011000000010001000010100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

