-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_2_19_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_2_19_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101111110101100110011010101", 1 => "10111100100011101001100100100000", 2 => "00111101110000000001010101111111", 3 => "00111110011000110111110101100011", 
    4 => "00111101101100101010000111111001", 5 => "00111101111011111111110010011000", 6 => "00111110000001111001111110101001", 7 => "00111101110011100111011110010010", 
    8 => "00111101101011000010101111011000", 9 => "00111101101101111011011000110101", 10 => "00111110101001100001001001100010", 11 => "00111101111100011000000100010111", 
    12 => "00111101110011100101110001001111", 13 => "10111101011000111000101110001011", 14 => "00111110001111001100010100110011", 15 => "10111110000100000011000000111100", 
    16 => "00111101100000111101000011000000", 17 => "00111101100011100101111101110100", 18 => "10111101110011101100110010000001", 19 => "00111101110010011000110101000111", 
    20 => "00111110001000111011010110111111", 21 => "10111101001110010000010000101110", 22 => "00111110010100110100110001011110", 23 => "10111101100010000011010101011001", 
    24 => "10111101010001010000001101110101", 25 => "10111101100000101001101111110001", 26 => "00111101111001111111111101011000", 27 => "00111110010100011010101110001111", 
    28 => "00111011010000101101011010101010", 29 => "10111101100111110111001011110111", 30 => "00111101111100001100000110111001", 31 => "10111101110101101010010000000001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

