-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l2_p_ZL2W2_0_6_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l2_p_ZL2W2_0_6_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101101100110110001101101111", 1 => "00111100100001110100100001011110", 2 => "00111101011010100001110101110101", 3 => "00111101110111111111001001011110", 
    4 => "10111100010000111000001010100001", 5 => "10111101110011100111010011110011", 6 => "10111110110100101000110110000110", 7 => "00111101100100101011010001010011", 
    8 => "10111110000001011101001101010110", 9 => "00111101001111011000101011011011", 10 => "00111101111001101101001101110100", 11 => "00111101001001010110011010001100", 
    12 => "10111100011110001000111111001001", 13 => "00111101000111111001001001101100", 14 => "10111101101010010010100100100100", 15 => "10111100101111100000011110100011", 
    16 => "10111101100100001010010011100011", 17 => "10111101100001100010101000011011", 18 => "00111101010100110010101101010110", 19 => "00111101001000011110011100010000", 
    20 => "00111100101111101000011110010000", 21 => "00111101111100111011000110001110", 22 => "10111101111101100001010001011001", 23 => "00111101010010001110010001110101", 
    24 => "10111101100001001000010110100001", 25 => "00111101111100100010100111101001", 26 => "10111100101100111101110100010010", 27 => "00111101100101100101101100100001", 
    28 => "00111101001110000110100011111101", 29 => "10111110000010011001111110100001", 30 => "00111101110110000001101011011111", 31 => "10111101111100110101101010000110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

