-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_1_32_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_1_32_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111100111000011001101110010001", 1 => "00111101011100000110000010111011", 2 => "10111101011000101011100011000111", 3 => "10111101000000010100111001111111", 
    4 => "10111100111111011100001101111010", 5 => "10111101010101000101111110011110", 6 => "10111100110001100110011011101101", 7 => "10111011101101100111001111000101", 
    8 => "00111100111001110000110000010011", 9 => "00111100101011000100010100000010", 10 => "00111101101010010001101110000010", 11 => "10111101101111000011110011100010", 
    12 => "10111101001001100100011011110001", 13 => "00111100110000110011000011010111", 14 => "10111100110001101011100010110111", 15 => "10111011010000111001111111111101", 
    16 => "10111101100111110001001110001100", 17 => "00111101001000111100011101010000", 18 => "10111101001100101100001100000001", 19 => "00111101100101111111100011001011", 
    20 => "10111101000011011100111011000000", 21 => "10111101110110010010110110011001", 22 => "00111101000100001111101101100101", 23 => "10111010111011111101110010011100", 
    24 => "00111101100101101010110001100100", 25 => "00111101101001000110110110000011", 26 => "00111010110001100111000101101001", 27 => "10111101011001000001000010110110", 
    28 => "00111101101000100111011010111000", 29 => "00111101101101010001001011101100", 30 => "10111101011111110100110110111110", 31 => "00111101011111101110000110111101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

