-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cloud_mlp_top_compute_l3_p_ZL2W3_0_104_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cloud_mlp_top_compute_l3_p_ZL2W3_0_104_RAM_2P_BRAM_1R1W is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111100111001001100001011111000", 1 => "10111100010000111010010000101111", 2 => "00111100111011100111010111111111", 3 => "00111100111000011101111010101101", 
    4 => "10111101101100011010100101110110", 5 => "10111101010001111100001100001101", 6 => "10111101100010101001100010101011", 7 => "00111101001011100011101101000111", 
    8 => "10111100111011001000011100010010", 9 => "00111101101001100011100111010110", 10 => "00111101100111111110101110001110", 11 => "10111101100111011000000111110001", 
    12 => "00111101010001000111111101010110", 13 => "00111100000000001110100011001001", 14 => "00111101100111010111100110001110", 15 => "10111101001111010100011010110010", 
    16 => "10111101100011011101101101010101", 17 => "00111011000101000100111011010111", 18 => "00111101000100100100101111111101", 19 => "00111101000101000100000100110101", 
    20 => "10111101101100001101110110000011", 21 => "00111101101001101010100011111100", 22 => "00111100110001011010010111111100", 23 => "00111101000111010001000110111110", 
    24 => "00111100010001101101111001110110", 25 => "10111011111000011010110001011000", 26 => "10111100100110110100011110000100", 27 => "00111100110100010011000011100000", 
    28 => "00111101000111011010100010111101", 29 => "10111100110001111001011100000011", 30 => "10111101101010111101101110100001", 31 => "10111101001001111000001110011101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

