# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/mlp_cloud_detection/mlp_cloud_detection.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mlp_cloud_detection || ORIG_REF_NAME==mlp_cloud_detection} -quiet] -quiet

# IP: bd/mlp_cloud_detection/ip/mlp_cloud_detection_zynq_ultra_ps_e_0_0/mlp_cloud_detection_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mlp_cloud_detection_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==mlp_cloud_detection_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/mlp_cloud_detection/ip/mlp_cloud_detection_ddr4_0_0/mlp_cloud_detection_ddr4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mlp_cloud_detection_ddr4_0_0 || ORIG_REF_NAME==mlp_cloud_detection_ddr4_0_0} -quiet] -quiet

# IP: bd/mlp_cloud_detection/ip/mlp_cloud_detection_axi_dma_0_0/mlp_cloud_detection_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mlp_cloud_detection_axi_dma_0_0 || ORIG_REF_NAME==mlp_cloud_detection_axi_dma_0_0} -quiet] -quiet

# IP: bd/mlp_cloud_detection/ip/mlp_cloud_detection_cloud_mlp_top_0_0/mlp_cloud_detection_cloud_mlp_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mlp_cloud_detection_cloud_mlp_top_0_0 || ORIG_REF_NAME==mlp_cloud_detection_cloud_mlp_top_0_0} -quiet] -quiet

# IP: bd/mlp_cloud_detection/ip/mlp_cloud_detection_axi_smc_0/mlp_cloud_detection_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mlp_cloud_detection_axi_smc_0 || ORIG_REF_NAME==mlp_cloud_detection_axi_smc_0} -quiet] -quiet

# IP: bd/mlp_cloud_detection/ip/mlp_cloud_detection_rst_ps8_0_99M_0/mlp_cloud_detection_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mlp_cloud_detection_rst_ps8_0_99M_0 || ORIG_REF_NAME==mlp_cloud_detection_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/mlp_cloud_detection/ip/mlp_cloud_detection_rst_ddr4_0_300M_0/mlp_cloud_detection_rst_ddr4_0_300M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mlp_cloud_detection_rst_ddr4_0_300M_0 || ORIG_REF_NAME==mlp_cloud_detection_rst_ddr4_0_300M_0} -quiet] -quiet

# IP: bd/mlp_cloud_detection/ip/mlp_cloud_detection_xlconcat_0_0/mlp_cloud_detection_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mlp_cloud_detection_xlconcat_0_0 || ORIG_REF_NAME==mlp_cloud_detection_xlconcat_0_0} -quiet] -quiet

# IP: bd/mlp_cloud_detection/ip/mlp_cloud_detection_axi_interconnect_0_imp_xbar_1/mlp_cloud_detection_axi_interconnect_0_imp_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mlp_cloud_detection_axi_interconnect_0_imp_xbar_1 || ORIG_REF_NAME==mlp_cloud_detection_axi_interconnect_0_imp_xbar_1} -quiet] -quiet

# IP: bd/mlp_cloud_detection/ip/mlp_cloud_detection_axi_interconnect_0_imp_auto_pc_0/mlp_cloud_detection_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mlp_cloud_detection_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==mlp_cloud_detection_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# IP: bd/mlp_cloud_detection/ip/mlp_cloud_detection_axi_interconnect_0_1/mlp_cloud_detection_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mlp_cloud_detection_axi_interconnect_0_1 || ORIG_REF_NAME==mlp_cloud_detection_axi_interconnect_0_1} -quiet] -quiet

# XDC: c:/OCDS/cloude-detection-accelerator/mlp_ip_generater/mlp_ip_generater.gen/sources_1/bd/mlp_cloud_detection/mlp_cloud_detection_ooc.xdc
