# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/OCDS/cloude-detection-accelerator/mlp_ip_generater/mlp_ip_generater.srcs/sources_1/bd/mlp_cloud_detection/ip/mlp_cloud_detection_cloud_mlp_top_0_0/mlp_cloud_detection_cloud_mlp_top_0_0.xci
# IP: The module: 'mlp_cloud_detection_cloud_mlp_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/OCDS/cloude-detection-accelerator/mlp_ip_generater/mlp_ip_generater.gen/sources_1/bd/mlp_cloud_detection/ip/mlp_cloud_detection_cloud_mlp_top_0_0/hdl/ip/cloud_mlp_top_fpext_32ns_64_1_no_dsp_1_ip/cloud_mlp_top_fpext_32ns_64_1_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cloud_mlp_top_fpext_32ns_64_1_no_dsp_1_ip || ORIG_REF_NAME==cloud_mlp_top_fpext_32ns_64_1_no_dsp_1_ip} -quiet] -quiet

# XDC: c:/OCDS/cloude-detection-accelerator/mlp_ip_generater/mlp_ip_generater.gen/sources_1/bd/mlp_cloud_detection/ip/mlp_cloud_detection_cloud_mlp_top_0_0/constraints/cloud_mlp_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mlp_cloud_detection_cloud_mlp_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/OCDS/cloude-detection-accelerator/mlp_ip_generater/mlp_ip_generater.srcs/sources_1/bd/mlp_cloud_detection/ip/mlp_cloud_detection_cloud_mlp_top_0_0/mlp_cloud_detection_cloud_mlp_top_0_0.xci
# IP: The module: 'mlp_cloud_detection_cloud_mlp_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/OCDS/cloude-detection-accelerator/mlp_ip_generater/mlp_ip_generater.gen/sources_1/bd/mlp_cloud_detection/ip/mlp_cloud_detection_cloud_mlp_top_0_0/hdl/ip/cloud_mlp_top_fpext_32ns_64_1_no_dsp_1_ip/cloud_mlp_top_fpext_32ns_64_1_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cloud_mlp_top_fpext_32ns_64_1_no_dsp_1_ip || ORIG_REF_NAME==cloud_mlp_top_fpext_32ns_64_1_no_dsp_1_ip} -quiet] -quiet

# XDC: c:/OCDS/cloude-detection-accelerator/mlp_ip_generater/mlp_ip_generater.gen/sources_1/bd/mlp_cloud_detection/ip/mlp_cloud_detection_cloud_mlp_top_0_0/constraints/cloud_mlp_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mlp_cloud_detection_cloud_mlp_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
